<?php
/**
 * PersonSkillsApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PHPR API
 *
 * PHPR API USING API-PLATFORM
 *
 * The version of the OpenAPI document: 3.7.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.18.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Test\Api;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * PersonSkillsApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class PersonSkillsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for apiPersonSkillsGetCollection
     *
     * Retrieves the collection of person_skills resources..
     *
     */
    public function testApiPersonSkillsGetCollection()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiPersonSkillsIdDelete
     *
     * Removes the person_skills resource..
     *
     */
    public function testApiPersonSkillsIdDelete()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiPersonSkillsIdGet
     *
     * Retrieves a person_skills resource..
     *
     */
    public function testApiPersonSkillsIdGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiPersonSkillsIdPut
     *
     * Replaces the person_skills resource..
     *
     */
    public function testApiPersonSkillsIdPut()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiPersonSkillsPost
     *
     * Creates a person_skills resource..
     *
     */
    public function testApiPersonSkillsPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for personSkillApiFileUpload
     *
     * Creates a person_skills resource..
     *
     */
    public function testPersonSkillApiFileUpload()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for personSkillDropDown
     *
     * Retrieves the collection of person_skills resources..
     *
     */
    public function testPersonSkillDropDown()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for personSkillDuplicate
     *
     * Retrieves a person_skills resource..
     *
     */
    public function testPersonSkillDuplicate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for personSkillFetchFiles
     *
     * Retrieves a person_skills resource..
     *
     */
    public function testPersonSkillFetchFiles()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for personSkillGetBySlug
     *
     * Retrieves a person_skills resource..
     *
     */
    public function testPersonSkillGetBySlug()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for personSkillGetDeleteRelations
     *
     * Retrieves a person_skills resource..
     *
     */
    public function testPersonSkillGetDeleteRelations()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for personSkillMetadata
     *
     * Retrieves a person_skills resource..
     *
     */
    public function testPersonSkillMetadata()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
