<?php
/**
 * PersonMarketingsourcesApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PHPR API
 *
 * PHPR API USING API-PLATFORM
 *
 * The version of the OpenAPI document: 3.7.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.18.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Test\Api;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * PersonMarketingsourcesApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class PersonMarketingsourcesApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for apiPersonMarketingsourcesGetCollection
     *
     * Retrieves the collection of person_marketingsources resources..
     *
     */
    public function testApiPersonMarketingsourcesGetCollection()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiPersonMarketingsourcesIdDelete
     *
     * Removes the person_marketingsources resource..
     *
     */
    public function testApiPersonMarketingsourcesIdDelete()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiPersonMarketingsourcesIdGet
     *
     * Retrieves a person_marketingsources resource..
     *
     */
    public function testApiPersonMarketingsourcesIdGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiPersonMarketingsourcesIdPut
     *
     * Replaces the person_marketingsources resource..
     *
     */
    public function testApiPersonMarketingsourcesIdPut()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiPersonMarketingsourcesPost
     *
     * Creates a person_marketingsources resource..
     *
     */
    public function testApiPersonMarketingsourcesPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for personMarketingSourceApiFileUpload
     *
     * Creates a person_marketingsources resource..
     *
     */
    public function testPersonMarketingSourceApiFileUpload()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for personMarketingSourceDropDown
     *
     * Retrieves the collection of person_marketingsources resources..
     *
     */
    public function testPersonMarketingSourceDropDown()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for personMarketingSourceDuplicate
     *
     * Retrieves a person_marketingsources resource..
     *
     */
    public function testPersonMarketingSourceDuplicate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for personMarketingSourceFetchFiles
     *
     * Retrieves a person_marketingsources resource..
     *
     */
    public function testPersonMarketingSourceFetchFiles()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for personMarketingSourceGetBySlug
     *
     * Retrieves a person_marketingsources resource..
     *
     */
    public function testPersonMarketingSourceGetBySlug()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for personMarketingSourceGetDeleteRelations
     *
     * Retrieves a person_marketingsources resource..
     *
     */
    public function testPersonMarketingSourceGetDeleteRelations()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for personMarketingSourceMetadata
     *
     * Retrieves a person_marketingsources resource..
     *
     */
    public function testPersonMarketingSourceMetadata()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
