<?php
/**
 * PersonEmployeeTypesApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PHPR API
 *
 * PHPR API USING API-PLATFORM
 *
 * The version of the OpenAPI document: 3.7.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.18.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Test\Api;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * PersonEmployeeTypesApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class PersonEmployeeTypesApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for apiPersonEmployeeTypesGetCollection
     *
     * Retrieves the collection of person_employee_types resources..
     *
     */
    public function testApiPersonEmployeeTypesGetCollection()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiPersonEmployeeTypesIdDelete
     *
     * Removes the person_employee_types resource..
     *
     */
    public function testApiPersonEmployeeTypesIdDelete()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiPersonEmployeeTypesIdGet
     *
     * Retrieves a person_employee_types resource..
     *
     */
    public function testApiPersonEmployeeTypesIdGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiPersonEmployeeTypesIdPut
     *
     * Replaces the person_employee_types resource..
     *
     */
    public function testApiPersonEmployeeTypesIdPut()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiPersonEmployeeTypesPost
     *
     * Creates a person_employee_types resource..
     *
     */
    public function testApiPersonEmployeeTypesPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for personEmployeeTypeApiFileUpload
     *
     * Creates a person_employee_types resource..
     *
     */
    public function testPersonEmployeeTypeApiFileUpload()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for personEmployeeTypeDropDown
     *
     * Retrieves the collection of person_employee_types resources..
     *
     */
    public function testPersonEmployeeTypeDropDown()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for personEmployeeTypeDuplicate
     *
     * Retrieves a person_employee_types resource..
     *
     */
    public function testPersonEmployeeTypeDuplicate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for personEmployeeTypeFetchFiles
     *
     * Retrieves a person_employee_types resource..
     *
     */
    public function testPersonEmployeeTypeFetchFiles()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for personEmployeeTypeGetBySlug
     *
     * Retrieves a person_employee_types resource..
     *
     */
    public function testPersonEmployeeTypeGetBySlug()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for personEmployeeTypeGetDeleteRelations
     *
     * Retrieves a person_employee_types resource..
     *
     */
    public function testPersonEmployeeTypeGetDeleteRelations()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for personEmployeeTypeMetadata
     *
     * Retrieves a person_employee_types resource..
     *
     */
    public function testPersonEmployeeTypeMetadata()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
