<?php
/**
 * TimesheetAllowanceTypesApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PHPR API
 *
 * PHPR API USING API-PLATFORM
 *
 * The version of the OpenAPI document: 3.7.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.18.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Test\Api;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * TimesheetAllowanceTypesApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class TimesheetAllowanceTypesApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for apiTimesheetAllowanceTypesGetCollection
     *
     * Retrieves the collection of timesheet_allowance_types resources..
     *
     */
    public function testApiTimesheetAllowanceTypesGetCollection()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiTimesheetAllowanceTypesIdDelete
     *
     * Removes the timesheet_allowance_types resource..
     *
     */
    public function testApiTimesheetAllowanceTypesIdDelete()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiTimesheetAllowanceTypesIdGet
     *
     * Retrieves a timesheet_allowance_types resource..
     *
     */
    public function testApiTimesheetAllowanceTypesIdGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiTimesheetAllowanceTypesIdPut
     *
     * Replaces the timesheet_allowance_types resource..
     *
     */
    public function testApiTimesheetAllowanceTypesIdPut()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiTimesheetAllowanceTypesPost
     *
     * Creates a timesheet_allowance_types resource..
     *
     */
    public function testApiTimesheetAllowanceTypesPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for timesheetAllowanceTypeApiFileUpload
     *
     * Creates a timesheet_allowance_types resource..
     *
     */
    public function testTimesheetAllowanceTypeApiFileUpload()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for timesheetAllowanceTypeDropDown
     *
     * Retrieves the collection of timesheet_allowance_types resources..
     *
     */
    public function testTimesheetAllowanceTypeDropDown()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for timesheetAllowanceTypeDuplicate
     *
     * Retrieves a timesheet_allowance_types resource..
     *
     */
    public function testTimesheetAllowanceTypeDuplicate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for timesheetAllowanceTypeFetchFiles
     *
     * Retrieves a timesheet_allowance_types resource..
     *
     */
    public function testTimesheetAllowanceTypeFetchFiles()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for timesheetAllowanceTypeGetBySlug
     *
     * Retrieves a timesheet_allowance_types resource..
     *
     */
    public function testTimesheetAllowanceTypeGetBySlug()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for timesheetAllowanceTypeGetDeleteRelations
     *
     * Retrieves a timesheet_allowance_types resource..
     *
     */
    public function testTimesheetAllowanceTypeGetDeleteRelations()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for timesheetAllowanceTypeMetadata
     *
     * Retrieves a timesheet_allowance_types resource..
     *
     */
    public function testTimesheetAllowanceTypeMetadata()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
