<?php
/**
 * CoordinateLocationsCoordinateLocationShowStandardShowNoteShowIdTimestampableTagTaggingListNoteRelationsCustomProperty
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PHPR API
 *
 * PHPR API USING API-PLATFORM
 *
 * The version of the OpenAPI document: 3.7.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.18.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * CoordinateLocationsCoordinateLocationShowStandardShowNoteShowIdTimestampableTagTaggingListNoteRelationsCustomProperty Class Doc Comment
 *
 * @category Class
 * @description Location.
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class CoordinateLocationsCoordinateLocationShowStandardShowNoteShowIdTimestampableTagTaggingListNoteRelationsCustomProperty implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'coordinate_locations-coordinateLocationShow_standardShow_noteShow_id_timestampable_tagTaggingList_noteRelations_customProperty';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'coordinates' => '\OpenAPI\Client\Model\CoordinatesCoordinateLocationShowStandardShowNoteShowIdTimestampableTagTaggingListNoteRelationsCustomProperty',
        'shipment' => '\OpenAPI\Client\Model\ShippingShipmentsCoordinateLocationShowStandardShowNoteShowIdTimestampableTagTaggingListNoteRelationsCustomProperty',
        'task' => '\OpenAPI\Client\Model\ProjectTasksCoordinateLocationShowStandardShowNoteShowIdTimestampableTagTaggingListNoteRelationsCustomProperty',
        'address' => 'string',
        'suite' => 'string',
        'road' => 'string',
        'city' => 'string',
        'state' => 'string',
        'country' => 'string',
        'postal_code' => 'string',
        'time_zone' => 'string',
        'note' => 'string',
        'owning_corporation' => '\OpenAPI\Client\Model\PersonCorporationsCoordinateLocationShowStandardShowNoteShowIdTimestampableTagTaggingListNoteRelationsCustomProperty',
        'tax_customs' => '\OpenAPI\Client\Model\FeeTaxCustomsCoordinateLocationShowStandardShowNoteShowIdTimestampableTagTaggingListNoteRelationsCustomProperty[]',
        'shortcode' => 'string',
        'deleted_at' => '\DateTime',
        'id' => 'int',
        'slug' => 'string',
        'custom_properties' => 'mixed',
        'custom_data' => 'string[]',
        'created_at' => '\DateTime',
        'updated_at' => '\DateTime',
        'disabled_at' => '\DateTime',
        'to_string' => 'string',
        'location_full_address' => 'string',
        'location_g_maps_query_string' => 'string',
        'coordinates_listing' => 'int',
        'custom_properties_listing' => 'string',
        'anonymous_token' => 'string',
        'unique_id' => 'string',
        'tagging_listing' => 'string',
        'enabled' => 'bool',
        'disabled' => 'bool'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'coordinates' => null,
        'shipment' => null,
        'task' => null,
        'address' => null,
        'suite' => null,
        'road' => null,
        'city' => null,
        'state' => null,
        'country' => null,
        'postal_code' => null,
        'time_zone' => null,
        'note' => null,
        'owning_corporation' => null,
        'tax_customs' => null,
        'shortcode' => null,
        'deleted_at' => 'date-time',
        'id' => null,
        'slug' => null,
        'custom_properties' => null,
        'custom_data' => null,
        'created_at' => 'date-time',
        'updated_at' => 'date-time',
        'disabled_at' => 'date-time',
        'to_string' => null,
        'location_full_address' => null,
        'location_g_maps_query_string' => null,
        'coordinates_listing' => null,
        'custom_properties_listing' => null,
        'anonymous_token' => null,
        'unique_id' => null,
        'tagging_listing' => null,
        'enabled' => null,
        'disabled' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'coordinates' => true,
        'shipment' => true,
        'task' => true,
        'address' => true,
        'suite' => true,
        'road' => true,
        'city' => true,
        'state' => true,
        'country' => false,
        'postal_code' => true,
        'time_zone' => true,
        'note' => true,
        'owning_corporation' => false,
        'tax_customs' => false,
        'shortcode' => false,
        'deleted_at' => true,
        'id' => false,
        'slug' => false,
        'custom_properties' => true,
        'custom_data' => true,
        'created_at' => false,
        'updated_at' => false,
        'disabled_at' => true,
        'to_string' => false,
        'location_full_address' => false,
        'location_g_maps_query_string' => false,
        'coordinates_listing' => false,
        'custom_properties_listing' => false,
        'anonymous_token' => false,
        'unique_id' => false,
        'tagging_listing' => false,
        'enabled' => false,
        'disabled' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'coordinates' => 'coordinates',
        'shipment' => 'shipment',
        'task' => 'task',
        'address' => 'address',
        'suite' => 'suite',
        'road' => 'road',
        'city' => 'city',
        'state' => 'state',
        'country' => 'country',
        'postal_code' => 'postalCode',
        'time_zone' => 'timeZone',
        'note' => 'note',
        'owning_corporation' => 'owningCorporation',
        'tax_customs' => 'taxCustoms',
        'shortcode' => 'shortcode',
        'deleted_at' => 'deletedAt',
        'id' => 'id',
        'slug' => 'slug',
        'custom_properties' => 'customProperties',
        'custom_data' => 'customData',
        'created_at' => 'createdAt',
        'updated_at' => 'updatedAt',
        'disabled_at' => 'disabledAt',
        'to_string' => 'toString',
        'location_full_address' => 'locationFullAddress',
        'location_g_maps_query_string' => 'locationGMapsQueryString',
        'coordinates_listing' => 'coordinatesListing',
        'custom_properties_listing' => 'customPropertiesListing',
        'anonymous_token' => 'anonymousToken',
        'unique_id' => 'uniqueId',
        'tagging_listing' => 'taggingListing',
        'enabled' => 'enabled',
        'disabled' => 'disabled'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'coordinates' => 'setCoordinates',
        'shipment' => 'setShipment',
        'task' => 'setTask',
        'address' => 'setAddress',
        'suite' => 'setSuite',
        'road' => 'setRoad',
        'city' => 'setCity',
        'state' => 'setState',
        'country' => 'setCountry',
        'postal_code' => 'setPostalCode',
        'time_zone' => 'setTimeZone',
        'note' => 'setNote',
        'owning_corporation' => 'setOwningCorporation',
        'tax_customs' => 'setTaxCustoms',
        'shortcode' => 'setShortcode',
        'deleted_at' => 'setDeletedAt',
        'id' => 'setId',
        'slug' => 'setSlug',
        'custom_properties' => 'setCustomProperties',
        'custom_data' => 'setCustomData',
        'created_at' => 'setCreatedAt',
        'updated_at' => 'setUpdatedAt',
        'disabled_at' => 'setDisabledAt',
        'to_string' => 'setToString',
        'location_full_address' => 'setLocationFullAddress',
        'location_g_maps_query_string' => 'setLocationGMapsQueryString',
        'coordinates_listing' => 'setCoordinatesListing',
        'custom_properties_listing' => 'setCustomPropertiesListing',
        'anonymous_token' => 'setAnonymousToken',
        'unique_id' => 'setUniqueId',
        'tagging_listing' => 'setTaggingListing',
        'enabled' => 'setEnabled',
        'disabled' => 'setDisabled'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'coordinates' => 'getCoordinates',
        'shipment' => 'getShipment',
        'task' => 'getTask',
        'address' => 'getAddress',
        'suite' => 'getSuite',
        'road' => 'getRoad',
        'city' => 'getCity',
        'state' => 'getState',
        'country' => 'getCountry',
        'postal_code' => 'getPostalCode',
        'time_zone' => 'getTimeZone',
        'note' => 'getNote',
        'owning_corporation' => 'getOwningCorporation',
        'tax_customs' => 'getTaxCustoms',
        'shortcode' => 'getShortcode',
        'deleted_at' => 'getDeletedAt',
        'id' => 'getId',
        'slug' => 'getSlug',
        'custom_properties' => 'getCustomProperties',
        'custom_data' => 'getCustomData',
        'created_at' => 'getCreatedAt',
        'updated_at' => 'getUpdatedAt',
        'disabled_at' => 'getDisabledAt',
        'to_string' => 'getToString',
        'location_full_address' => 'getLocationFullAddress',
        'location_g_maps_query_string' => 'getLocationGMapsQueryString',
        'coordinates_listing' => 'getCoordinatesListing',
        'custom_properties_listing' => 'getCustomPropertiesListing',
        'anonymous_token' => 'getAnonymousToken',
        'unique_id' => 'getUniqueId',
        'tagging_listing' => 'getTaggingListing',
        'enabled' => 'getEnabled',
        'disabled' => 'getDisabled'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('coordinates', $data ?? [], null);
        $this->setIfExists('shipment', $data ?? [], null);
        $this->setIfExists('task', $data ?? [], null);
        $this->setIfExists('address', $data ?? [], null);
        $this->setIfExists('suite', $data ?? [], null);
        $this->setIfExists('road', $data ?? [], null);
        $this->setIfExists('city', $data ?? [], null);
        $this->setIfExists('state', $data ?? [], 'QC');
        $this->setIfExists('country', $data ?? [], 'CANADA');
        $this->setIfExists('postal_code', $data ?? [], null);
        $this->setIfExists('time_zone', $data ?? [], null);
        $this->setIfExists('note', $data ?? [], null);
        $this->setIfExists('owning_corporation', $data ?? [], null);
        $this->setIfExists('tax_customs', $data ?? [], null);
        $this->setIfExists('shortcode', $data ?? [], 'CRL');
        $this->setIfExists('deleted_at', $data ?? [], null);
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('slug', $data ?? [], null);
        $this->setIfExists('custom_properties', $data ?? [], null);
        $this->setIfExists('custom_data', $data ?? [], null);
        $this->setIfExists('created_at', $data ?? [], null);
        $this->setIfExists('updated_at', $data ?? [], null);
        $this->setIfExists('disabled_at', $data ?? [], null);
        $this->setIfExists('to_string', $data ?? [], null);
        $this->setIfExists('location_full_address', $data ?? [], null);
        $this->setIfExists('location_g_maps_query_string', $data ?? [], null);
        $this->setIfExists('coordinates_listing', $data ?? [], null);
        $this->setIfExists('custom_properties_listing', $data ?? [], null);
        $this->setIfExists('anonymous_token', $data ?? [], null);
        $this->setIfExists('unique_id', $data ?? [], null);
        $this->setIfExists('tagging_listing', $data ?? [], null);
        $this->setIfExists('enabled', $data ?? [], null);
        $this->setIfExists('disabled', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['country'] === null) {
            $invalidProperties[] = "'country' can't be null";
        }
        if ($this->container['slug'] === null) {
            $invalidProperties[] = "'slug' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets coordinates
     *
     * @return \OpenAPI\Client\Model\CoordinatesCoordinateLocationShowStandardShowNoteShowIdTimestampableTagTaggingListNoteRelationsCustomProperty|null
     */
    public function getCoordinates()
    {
        return $this->container['coordinates'];
    }

    /**
     * Sets coordinates
     *
     * @param \OpenAPI\Client\Model\CoordinatesCoordinateLocationShowStandardShowNoteShowIdTimestampableTagTaggingListNoteRelationsCustomProperty|null $coordinates coordinates
     *
     * @return self
     */
    public function setCoordinates($coordinates)
    {
        if (is_null($coordinates)) {
            array_push($this->openAPINullablesSetToNull, 'coordinates');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('coordinates', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['coordinates'] = $coordinates;

        return $this;
    }

    /**
     * Gets shipment
     *
     * @return \OpenAPI\Client\Model\ShippingShipmentsCoordinateLocationShowStandardShowNoteShowIdTimestampableTagTaggingListNoteRelationsCustomProperty|null
     */
    public function getShipment()
    {
        return $this->container['shipment'];
    }

    /**
     * Sets shipment
     *
     * @param \OpenAPI\Client\Model\ShippingShipmentsCoordinateLocationShowStandardShowNoteShowIdTimestampableTagTaggingListNoteRelationsCustomProperty|null $shipment shipment
     *
     * @return self
     */
    public function setShipment($shipment)
    {
        if (is_null($shipment)) {
            array_push($this->openAPINullablesSetToNull, 'shipment');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('shipment', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['shipment'] = $shipment;

        return $this;
    }

    /**
     * Gets task
     *
     * @return \OpenAPI\Client\Model\ProjectTasksCoordinateLocationShowStandardShowNoteShowIdTimestampableTagTaggingListNoteRelationsCustomProperty|null
     */
    public function getTask()
    {
        return $this->container['task'];
    }

    /**
     * Sets task
     *
     * @param \OpenAPI\Client\Model\ProjectTasksCoordinateLocationShowStandardShowNoteShowIdTimestampableTagTaggingListNoteRelationsCustomProperty|null $task task
     *
     * @return self
     */
    public function setTask($task)
    {
        if (is_null($task)) {
            array_push($this->openAPINullablesSetToNull, 'task');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('task', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['task'] = $task;

        return $this;
    }

    /**
     * Gets address
     *
     * @return string|null
     */
    public function getAddress()
    {
        return $this->container['address'];
    }

    /**
     * Sets address
     *
     * @param string|null $address address
     *
     * @return self
     */
    public function setAddress($address)
    {
        if (is_null($address)) {
            array_push($this->openAPINullablesSetToNull, 'address');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('address', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['address'] = $address;

        return $this;
    }

    /**
     * Gets suite
     *
     * @return string|null
     */
    public function getSuite()
    {
        return $this->container['suite'];
    }

    /**
     * Sets suite
     *
     * @param string|null $suite suite
     *
     * @return self
     */
    public function setSuite($suite)
    {
        if (is_null($suite)) {
            array_push($this->openAPINullablesSetToNull, 'suite');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('suite', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['suite'] = $suite;

        return $this;
    }

    /**
     * Gets road
     *
     * @return string|null
     */
    public function getRoad()
    {
        return $this->container['road'];
    }

    /**
     * Sets road
     *
     * @param string|null $road road
     *
     * @return self
     */
    public function setRoad($road)
    {
        if (is_null($road)) {
            array_push($this->openAPINullablesSetToNull, 'road');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('road', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['road'] = $road;

        return $this;
    }

    /**
     * Gets city
     *
     * @return string|null
     */
    public function getCity()
    {
        return $this->container['city'];
    }

    /**
     * Sets city
     *
     * @param string|null $city city
     *
     * @return self
     */
    public function setCity($city)
    {
        if (is_null($city)) {
            array_push($this->openAPINullablesSetToNull, 'city');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('city', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['city'] = $city;

        return $this;
    }

    /**
     * Gets state
     *
     * @return string|null
     */
    public function getState()
    {
        return $this->container['state'];
    }

    /**
     * Sets state
     *
     * @param string|null $state state
     *
     * @return self
     */
    public function setState($state)
    {
        if (is_null($state)) {
            array_push($this->openAPINullablesSetToNull, 'state');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('state', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['state'] = $state;

        return $this;
    }

    /**
     * Gets country
     *
     * @return string
     */
    public function getCountry()
    {
        return $this->container['country'];
    }

    /**
     * Sets country
     *
     * @param string $country country
     *
     * @return self
     */
    public function setCountry($country)
    {
        if (is_null($country)) {
            throw new \InvalidArgumentException('non-nullable country cannot be null');
        }
        $this->container['country'] = $country;

        return $this;
    }

    /**
     * Gets postal_code
     *
     * @return string|null
     */
    public function getPostalCode()
    {
        return $this->container['postal_code'];
    }

    /**
     * Sets postal_code
     *
     * @param string|null $postal_code postal_code
     *
     * @return self
     */
    public function setPostalCode($postal_code)
    {
        if (is_null($postal_code)) {
            array_push($this->openAPINullablesSetToNull, 'postal_code');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('postal_code', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['postal_code'] = $postal_code;

        return $this;
    }

    /**
     * Gets time_zone
     *
     * @return string|null
     */
    public function getTimeZone()
    {
        return $this->container['time_zone'];
    }

    /**
     * Sets time_zone
     *
     * @param string|null $time_zone time_zone
     *
     * @return self
     */
    public function setTimeZone($time_zone)
    {
        if (is_null($time_zone)) {
            array_push($this->openAPINullablesSetToNull, 'time_zone');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('time_zone', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['time_zone'] = $time_zone;

        return $this;
    }

    /**
     * Gets note
     *
     * @return string|null
     */
    public function getNote()
    {
        return $this->container['note'];
    }

    /**
     * Sets note
     *
     * @param string|null $note note
     *
     * @return self
     */
    public function setNote($note)
    {
        if (is_null($note)) {
            array_push($this->openAPINullablesSetToNull, 'note');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('note', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['note'] = $note;

        return $this;
    }

    /**
     * Gets owning_corporation
     *
     * @return \OpenAPI\Client\Model\PersonCorporationsCoordinateLocationShowStandardShowNoteShowIdTimestampableTagTaggingListNoteRelationsCustomProperty|null
     */
    public function getOwningCorporation()
    {
        return $this->container['owning_corporation'];
    }

    /**
     * Sets owning_corporation
     *
     * @param \OpenAPI\Client\Model\PersonCorporationsCoordinateLocationShowStandardShowNoteShowIdTimestampableTagTaggingListNoteRelationsCustomProperty|null $owning_corporation owning_corporation
     *
     * @return self
     */
    public function setOwningCorporation($owning_corporation)
    {
        if (is_null($owning_corporation)) {
            throw new \InvalidArgumentException('non-nullable owning_corporation cannot be null');
        }
        $this->container['owning_corporation'] = $owning_corporation;

        return $this;
    }

    /**
     * Gets tax_customs
     *
     * @return \OpenAPI\Client\Model\FeeTaxCustomsCoordinateLocationShowStandardShowNoteShowIdTimestampableTagTaggingListNoteRelationsCustomProperty[]|null
     */
    public function getTaxCustoms()
    {
        return $this->container['tax_customs'];
    }

    /**
     * Sets tax_customs
     *
     * @param \OpenAPI\Client\Model\FeeTaxCustomsCoordinateLocationShowStandardShowNoteShowIdTimestampableTagTaggingListNoteRelationsCustomProperty[]|null $tax_customs tax_customs
     *
     * @return self
     */
    public function setTaxCustoms($tax_customs)
    {
        if (is_null($tax_customs)) {
            throw new \InvalidArgumentException('non-nullable tax_customs cannot be null');
        }
        $this->container['tax_customs'] = $tax_customs;

        return $this;
    }

    /**
     * Gets shortcode
     *
     * @return string|null
     */
    public function getShortcode()
    {
        return $this->container['shortcode'];
    }

    /**
     * Sets shortcode
     *
     * @param string|null $shortcode shortcode
     *
     * @return self
     */
    public function setShortcode($shortcode)
    {
        if (is_null($shortcode)) {
            throw new \InvalidArgumentException('non-nullable shortcode cannot be null');
        }
        $this->container['shortcode'] = $shortcode;

        return $this;
    }

    /**
     * Gets deleted_at
     *
     * @return \DateTime|null
     */
    public function getDeletedAt()
    {
        return $this->container['deleted_at'];
    }

    /**
     * Sets deleted_at
     *
     * @param \DateTime|null $deleted_at deleted_at
     *
     * @return self
     */
    public function setDeletedAt($deleted_at)
    {
        if (is_null($deleted_at)) {
            array_push($this->openAPINullablesSetToNull, 'deleted_at');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('deleted_at', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['deleted_at'] = $deleted_at;

        return $this;
    }

    /**
     * Gets id
     *
     * @return int|null
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param int|null $id DB Identifier
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets slug
     *
     * @return string
     */
    public function getSlug()
    {
        return $this->container['slug'];
    }

    /**
     * Sets slug
     *
     * @param string $slug DB Identifier
     *
     * @return self
     */
    public function setSlug($slug)
    {
        if (is_null($slug)) {
            throw new \InvalidArgumentException('non-nullable slug cannot be null');
        }
        $this->container['slug'] = $slug;

        return $this;
    }

    /**
     * Gets custom_properties
     *
     * @return mixed|null
     */
    public function getCustomProperties()
    {
        return $this->container['custom_properties'];
    }

    /**
     * Sets custom_properties
     *
     * @param mixed|null $custom_properties custom_properties
     *
     * @return self
     */
    public function setCustomProperties($custom_properties)
    {
        if (is_null($custom_properties)) {
            array_push($this->openAPINullablesSetToNull, 'custom_properties');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('custom_properties', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['custom_properties'] = $custom_properties;

        return $this;
    }

    /**
     * Gets custom_data
     *
     * @return string[]|null
     */
    public function getCustomData()
    {
        return $this->container['custom_data'];
    }

    /**
     * Sets custom_data
     *
     * @param string[]|null $custom_data custom_data
     *
     * @return self
     */
    public function setCustomData($custom_data)
    {
        if (is_null($custom_data)) {
            array_push($this->openAPINullablesSetToNull, 'custom_data');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('custom_data', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['custom_data'] = $custom_data;

        return $this;
    }

    /**
     * Gets created_at
     *
     * @return \DateTime|null
     */
    public function getCreatedAt()
    {
        return $this->container['created_at'];
    }

    /**
     * Sets created_at
     *
     * @param \DateTime|null $created_at created_at
     *
     * @return self
     */
    public function setCreatedAt($created_at)
    {
        if (is_null($created_at)) {
            throw new \InvalidArgumentException('non-nullable created_at cannot be null');
        }
        $this->container['created_at'] = $created_at;

        return $this;
    }

    /**
     * Gets updated_at
     *
     * @return \DateTime|null
     */
    public function getUpdatedAt()
    {
        return $this->container['updated_at'];
    }

    /**
     * Sets updated_at
     *
     * @param \DateTime|null $updated_at updated_at
     *
     * @return self
     */
    public function setUpdatedAt($updated_at)
    {
        if (is_null($updated_at)) {
            throw new \InvalidArgumentException('non-nullable updated_at cannot be null');
        }
        $this->container['updated_at'] = $updated_at;

        return $this;
    }

    /**
     * Gets disabled_at
     *
     * @return \DateTime|null
     */
    public function getDisabledAt()
    {
        return $this->container['disabled_at'];
    }

    /**
     * Sets disabled_at
     *
     * @param \DateTime|null $disabled_at disabled_at
     *
     * @return self
     */
    public function setDisabledAt($disabled_at)
    {
        if (is_null($disabled_at)) {
            array_push($this->openAPINullablesSetToNull, 'disabled_at');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('disabled_at', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['disabled_at'] = $disabled_at;

        return $this;
    }

    /**
     * Gets to_string
     *
     * @return string|null
     */
    public function getToString()
    {
        return $this->container['to_string'];
    }

    /**
     * Sets to_string
     *
     * @param string|null $to_string to_string
     *
     * @return self
     */
    public function setToString($to_string)
    {
        if (is_null($to_string)) {
            throw new \InvalidArgumentException('non-nullable to_string cannot be null');
        }
        $this->container['to_string'] = $to_string;

        return $this;
    }

    /**
     * Gets location_full_address
     *
     * @return string|null
     */
    public function getLocationFullAddress()
    {
        return $this->container['location_full_address'];
    }

    /**
     * Sets location_full_address
     *
     * @param string|null $location_full_address location_full_address
     *
     * @return self
     */
    public function setLocationFullAddress($location_full_address)
    {
        if (is_null($location_full_address)) {
            throw new \InvalidArgumentException('non-nullable location_full_address cannot be null');
        }
        $this->container['location_full_address'] = $location_full_address;

        return $this;
    }

    /**
     * Gets location_g_maps_query_string
     *
     * @return string|null
     */
    public function getLocationGMapsQueryString()
    {
        return $this->container['location_g_maps_query_string'];
    }

    /**
     * Sets location_g_maps_query_string
     *
     * @param string|null $location_g_maps_query_string location_g_maps_query_string
     *
     * @return self
     */
    public function setLocationGMapsQueryString($location_g_maps_query_string)
    {
        if (is_null($location_g_maps_query_string)) {
            throw new \InvalidArgumentException('non-nullable location_g_maps_query_string cannot be null');
        }
        $this->container['location_g_maps_query_string'] = $location_g_maps_query_string;

        return $this;
    }

    /**
     * Gets coordinates_listing
     *
     * @return int|null
     */
    public function getCoordinatesListing()
    {
        return $this->container['coordinates_listing'];
    }

    /**
     * Sets coordinates_listing
     *
     * @param int|null $coordinates_listing Get coordinates.
     *
     * @return self
     */
    public function setCoordinatesListing($coordinates_listing)
    {
        if (is_null($coordinates_listing)) {
            throw new \InvalidArgumentException('non-nullable coordinates_listing cannot be null');
        }
        $this->container['coordinates_listing'] = $coordinates_listing;

        return $this;
    }

    /**
     * Gets custom_properties_listing
     *
     * @return string|null
     */
    public function getCustomPropertiesListing()
    {
        return $this->container['custom_properties_listing'];
    }

    /**
     * Sets custom_properties_listing
     *
     * @param string|null $custom_properties_listing custom_properties_listing
     *
     * @return self
     */
    public function setCustomPropertiesListing($custom_properties_listing)
    {
        if (is_null($custom_properties_listing)) {
            throw new \InvalidArgumentException('non-nullable custom_properties_listing cannot be null');
        }
        $this->container['custom_properties_listing'] = $custom_properties_listing;

        return $this;
    }

    /**
     * Gets anonymous_token
     *
     * @return string|null
     */
    public function getAnonymousToken()
    {
        return $this->container['anonymous_token'];
    }

    /**
     * Sets anonymous_token
     *
     * @param string|null $anonymous_token anonymous_token
     *
     * @return self
     */
    public function setAnonymousToken($anonymous_token)
    {
        if (is_null($anonymous_token)) {
            throw new \InvalidArgumentException('non-nullable anonymous_token cannot be null');
        }
        $this->container['anonymous_token'] = $anonymous_token;

        return $this;
    }

    /**
     * Gets unique_id
     *
     * @return string|null
     */
    public function getUniqueId()
    {
        return $this->container['unique_id'];
    }

    /**
     * Sets unique_id
     *
     * @param string|null $unique_id unique_id
     *
     * @return self
     */
    public function setUniqueId($unique_id)
    {
        if (is_null($unique_id)) {
            throw new \InvalidArgumentException('non-nullable unique_id cannot be null');
        }
        $this->container['unique_id'] = $unique_id;

        return $this;
    }

    /**
     * Gets tagging_listing
     *
     * @return string|null
     */
    public function getTaggingListing()
    {
        return $this->container['tagging_listing'];
    }

    /**
     * Sets tagging_listing
     *
     * @param string|null $tagging_listing Get Tagging Listing Why this crashes get annotations (proxy class?)
     *
     * @return self
     */
    public function setTaggingListing($tagging_listing)
    {
        if (is_null($tagging_listing)) {
            throw new \InvalidArgumentException('non-nullable tagging_listing cannot be null');
        }
        $this->container['tagging_listing'] = $tagging_listing;

        return $this;
    }

    /**
     * Gets enabled
     *
     * @return bool|null
     */
    public function getEnabled()
    {
        return $this->container['enabled'];
    }

    /**
     * Sets enabled
     *
     * @param bool|null $enabled Check if the entity is enabled.
     *
     * @return self
     */
    public function setEnabled($enabled)
    {
        if (is_null($enabled)) {
            throw new \InvalidArgumentException('non-nullable enabled cannot be null');
        }
        $this->container['enabled'] = $enabled;

        return $this;
    }

    /**
     * Gets disabled
     *
     * @return bool|null
     */
    public function getDisabled()
    {
        return $this->container['disabled'];
    }

    /**
     * Sets disabled
     *
     * @param bool|null $disabled Check if the entit is enabled.
     *
     * @return self
     */
    public function setDisabled($disabled)
    {
        if (is_null($disabled)) {
            throw new \InvalidArgumentException('non-nullable disabled cannot be null');
        }
        $this->container['disabled'] = $disabled;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


