<?php
/**
 * DataanalysisDatacollectorsJsonhal
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PHPR API
 *
 * PHPR API USING API-PLATFORM
 *
 * The version of the OpenAPI document: 3.7.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.18.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * DataanalysisDatacollectorsJsonhal Class Doc Comment
 *
 * @category Class
 * @description DataCollector.
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class DataanalysisDatacollectorsJsonhal implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'dataanalysis_datacollectors.jsonhal';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        '_links' => '\OpenAPI\Client\Model\AccessTokenJsonhalLinks',
        'title' => 'string',
        'description' => 'string',
        'directives' => 'string',
        'serialization_groups' => 'string',
        'data_processors' => 'string[]',
        'role' => 'string',
        'type' => 'int',
        'notes' => 'string',
        'filters' => 'string[]',
        'data_collector_parameters' => 'string[]',
        'data_collector_results' => 'string[]',
        'shortcode' => 'string',
        'deleted_at' => '\DateTime',
        'id' => 'int',
        'slug' => 'string',
        'custom_properties' => 'mixed',
        'custom_data' => 'string[]',
        'created_at' => '\DateTime',
        'updated_at' => '\DateTime',
        'tags' => 'string[]',
        'disabled_at' => '\DateTime',
        'entity_files' => '\OpenAPI\Client\Model\CollectionJsonhal',
        'upload_filename' => 'string',
        'upload_subfolder' => 'string',
        'upload_file' => 'string',
        'upload_file_link' => 'string',
        'to_string' => 'string',
        'directives_formatted' => 'string',
        'directives_formatted_api' => 'string',
        'parameter_names_array' => 'string[]',
        'parameter_operators_array' => 'string[]',
        'serialization_groups_array' => 'string[]',
        'parameter_default_values_array' => 'string[]',
        'parameter_types_array' => 'string[]',
        'result_names_array' => 'string[]',
        'filter_names_array' => 'string[]',
        'data_processors_listing' => 'string',
        'type_string' => 'string',
        'filters_listing' => 'string',
        'sorted_filters' => 'string[]',
        'data_collector_parameters_listing' => 'string',
        'data_collector_results_listing' => 'string',
        'data_processor_collectors_listing' => 'mixed',
        'request_params_listing' => 'string[]',
        'api_shortname' => 'string',
        'table_name' => 'string',
        'full_entity_string' => 'string',
        'anonymous_token' => 'string',
        'token_string' => 'string',
        'entity_metatada_endpoint' => 'string',
        'files_listing' => 'string',
        'modification_history_listing' => 'string',
        'notes_listing' => 'string',
        'ownerships_listing' => 'string',
        'approvals_listing' => 'string',
        'f_qcn' => 'string',
        'unique_id' => 'string',
        'api_custom_data' => 'mixed',
        'timestamp' => '\DateTime',
        'deleted' => 'bool',
        'taggable_type' => 'string',
        'taggable_id' => 'int',
        'tagging_listing' => 'string',
        'enabled' => 'bool',
        'enabled_virtual' => 'bool',
        'disabled' => 'bool',
        'upload_subfolder' => 'string',
        'upload_file' => 'string',
        'upload_file_link' => 'string',
        'entity_storage_folder' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        '_links' => null,
        'title' => null,
        'description' => null,
        'directives' => null,
        'serialization_groups' => null,
        'data_processors' => 'iri-reference',
        'role' => null,
        'type' => null,
        'notes' => null,
        'filters' => 'iri-reference',
        'data_collector_parameters' => 'iri-reference',
        'data_collector_results' => 'iri-reference',
        'shortcode' => null,
        'deleted_at' => 'date-time',
        'id' => null,
        'slug' => null,
        'custom_properties' => null,
        'custom_data' => null,
        'created_at' => 'date-time',
        'updated_at' => 'date-time',
        'tags' => null,
        'disabled_at' => 'date-time',
        'entity_files' => null,
        'upload_filename' => null,
        'upload_subfolder' => null,
        'upload_file' => null,
        'upload_file_link' => null,
        'to_string' => null,
        'directives_formatted' => null,
        'directives_formatted_api' => null,
        'parameter_names_array' => null,
        'parameter_operators_array' => null,
        'serialization_groups_array' => null,
        'parameter_default_values_array' => null,
        'parameter_types_array' => null,
        'result_names_array' => null,
        'filter_names_array' => null,
        'data_processors_listing' => null,
        'type_string' => null,
        'filters_listing' => null,
        'sorted_filters' => null,
        'data_collector_parameters_listing' => null,
        'data_collector_results_listing' => null,
        'data_processor_collectors_listing' => null,
        'request_params_listing' => null,
        'api_shortname' => null,
        'table_name' => null,
        'full_entity_string' => null,
        'anonymous_token' => null,
        'token_string' => null,
        'entity_metatada_endpoint' => null,
        'files_listing' => null,
        'modification_history_listing' => null,
        'notes_listing' => null,
        'ownerships_listing' => null,
        'approvals_listing' => null,
        'f_qcn' => null,
        'unique_id' => null,
        'api_custom_data' => null,
        'timestamp' => 'date-time',
        'deleted' => null,
        'taggable_type' => null,
        'taggable_id' => null,
        'tagging_listing' => null,
        'enabled' => null,
        'enabled_virtual' => null,
        'disabled' => null,
        'upload_subfolder' => null,
        'upload_file' => null,
        'upload_file_link' => null,
        'entity_storage_folder' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        '_links' => false,
        'title' => false,
        'description' => true,
        'directives' => false,
        'serialization_groups' => true,
        'data_processors' => false,
        'role' => false,
        'type' => false,
        'notes' => true,
        'filters' => false,
        'data_collector_parameters' => false,
        'data_collector_results' => false,
        'shortcode' => false,
        'deleted_at' => true,
        'id' => false,
        'slug' => false,
        'custom_properties' => true,
        'custom_data' => true,
        'created_at' => false,
        'updated_at' => false,
        'tags' => false,
        'disabled_at' => true,
        'entity_files' => false,
        'upload_filename' => false,
        'upload_subfolder' => false,
        'upload_file' => false,
        'upload_file_link' => false,
        'to_string' => false,
        'directives_formatted' => false,
        'directives_formatted_api' => false,
        'parameter_names_array' => false,
        'parameter_operators_array' => false,
        'serialization_groups_array' => false,
        'parameter_default_values_array' => false,
        'parameter_types_array' => false,
        'result_names_array' => false,
        'filter_names_array' => false,
        'data_processors_listing' => false,
        'type_string' => false,
        'filters_listing' => false,
        'sorted_filters' => false,
        'data_collector_parameters_listing' => false,
        'data_collector_results_listing' => false,
        'data_processor_collectors_listing' => true,
        'request_params_listing' => false,
        'api_shortname' => false,
        'table_name' => false,
        'full_entity_string' => false,
        'anonymous_token' => false,
        'token_string' => false,
        'entity_metatada_endpoint' => false,
        'files_listing' => false,
        'modification_history_listing' => false,
        'notes_listing' => false,
        'ownerships_listing' => false,
        'approvals_listing' => false,
        'f_qcn' => false,
        'unique_id' => false,
        'api_custom_data' => true,
        'timestamp' => false,
        'deleted' => false,
        'taggable_type' => true,
        'taggable_id' => false,
        'tagging_listing' => false,
        'enabled' => false,
        'enabled_virtual' => false,
        'disabled' => false,
        'upload_subfolder' => false,
        'upload_file' => false,
        'upload_file_link' => false,
        'entity_storage_folder' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        '_links' => '_links',
        'title' => 'title',
        'description' => 'description',
        'directives' => 'directives',
        'serialization_groups' => 'serializationGroups',
        'data_processors' => 'dataProcessors',
        'role' => 'role',
        'type' => 'type',
        'notes' => 'notes',
        'filters' => 'filters',
        'data_collector_parameters' => 'dataCollectorParameters',
        'data_collector_results' => 'dataCollectorResults',
        'shortcode' => 'shortcode',
        'deleted_at' => 'deletedAt',
        'id' => 'id',
        'slug' => 'slug',
        'custom_properties' => 'customProperties',
        'custom_data' => 'customData',
        'created_at' => 'createdAt',
        'updated_at' => 'updatedAt',
        'tags' => 'tags',
        'disabled_at' => 'disabledAt',
        'entity_files' => 'entityFiles',
        'upload_filename' => 'upload_filename',
        'upload_subfolder' => 'upload_subfolder',
        'upload_file' => 'upload_file',
        'upload_file_link' => 'upload_file_link',
        'to_string' => 'toString',
        'directives_formatted' => 'directivesFormatted',
        'directives_formatted_api' => 'directivesFormattedApi',
        'parameter_names_array' => 'parameterNamesArray',
        'parameter_operators_array' => 'parameterOperatorsArray',
        'serialization_groups_array' => 'serializationGroupsArray',
        'parameter_default_values_array' => 'parameterDefaultValuesArray',
        'parameter_types_array' => 'parameterTypesArray',
        'result_names_array' => 'resultNamesArray',
        'filter_names_array' => 'filterNamesArray',
        'data_processors_listing' => 'dataProcessorsListing',
        'type_string' => 'typeString',
        'filters_listing' => 'filtersListing',
        'sorted_filters' => 'sortedFilters',
        'data_collector_parameters_listing' => 'dataCollectorParametersListing',
        'data_collector_results_listing' => 'dataCollectorResultsListing',
        'data_processor_collectors_listing' => 'dataProcessorCollectorsListing',
        'request_params_listing' => 'requestParamsListing',
        'api_shortname' => 'apiShortname',
        'table_name' => 'tableName',
        'full_entity_string' => 'fullEntityString',
        'anonymous_token' => 'anonymousToken',
        'token_string' => 'tokenString',
        'entity_metatada_endpoint' => 'entityMetatadaEndpoint',
        'files_listing' => 'filesListing',
        'modification_history_listing' => 'modificationHistoryListing',
        'notes_listing' => 'notesListing',
        'ownerships_listing' => 'ownershipsListing',
        'approvals_listing' => 'approvalsListing',
        'f_qcn' => 'fQCN',
        'unique_id' => 'uniqueId',
        'api_custom_data' => 'apiCustomData',
        'timestamp' => 'timestamp',
        'deleted' => 'deleted',
        'taggable_type' => 'taggableType',
        'taggable_id' => 'taggableId',
        'tagging_listing' => 'taggingListing',
        'enabled' => 'enabled',
        'enabled_virtual' => 'enabledVirtual',
        'disabled' => 'disabled',
        'upload_subfolder' => 'upload_Subfolder',
        'upload_file' => 'upload_File',
        'upload_file_link' => 'upload_File_Link',
        'entity_storage_folder' => 'entityStorageFolder'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        '_links' => 'setLinks',
        'title' => 'setTitle',
        'description' => 'setDescription',
        'directives' => 'setDirectives',
        'serialization_groups' => 'setSerializationGroups',
        'data_processors' => 'setDataProcessors',
        'role' => 'setRole',
        'type' => 'setType',
        'notes' => 'setNotes',
        'filters' => 'setFilters',
        'data_collector_parameters' => 'setDataCollectorParameters',
        'data_collector_results' => 'setDataCollectorResults',
        'shortcode' => 'setShortcode',
        'deleted_at' => 'setDeletedAt',
        'id' => 'setId',
        'slug' => 'setSlug',
        'custom_properties' => 'setCustomProperties',
        'custom_data' => 'setCustomData',
        'created_at' => 'setCreatedAt',
        'updated_at' => 'setUpdatedAt',
        'tags' => 'setTags',
        'disabled_at' => 'setDisabledAt',
        'entity_files' => 'setEntityFiles',
        'upload_filename' => 'setUploadFilename',
        'upload_subfolder' => 'setUploadSubfolder',
        'upload_file' => 'setUploadFile',
        'upload_file_link' => 'setUploadFileLink',
        'to_string' => 'setToString',
        'directives_formatted' => 'setDirectivesFormatted',
        'directives_formatted_api' => 'setDirectivesFormattedApi',
        'parameter_names_array' => 'setParameterNamesArray',
        'parameter_operators_array' => 'setParameterOperatorsArray',
        'serialization_groups_array' => 'setSerializationGroupsArray',
        'parameter_default_values_array' => 'setParameterDefaultValuesArray',
        'parameter_types_array' => 'setParameterTypesArray',
        'result_names_array' => 'setResultNamesArray',
        'filter_names_array' => 'setFilterNamesArray',
        'data_processors_listing' => 'setDataProcessorsListing',
        'type_string' => 'setTypeString',
        'filters_listing' => 'setFiltersListing',
        'sorted_filters' => 'setSortedFilters',
        'data_collector_parameters_listing' => 'setDataCollectorParametersListing',
        'data_collector_results_listing' => 'setDataCollectorResultsListing',
        'data_processor_collectors_listing' => 'setDataProcessorCollectorsListing',
        'request_params_listing' => 'setRequestParamsListing',
        'api_shortname' => 'setApiShortname',
        'table_name' => 'setTableName',
        'full_entity_string' => 'setFullEntityString',
        'anonymous_token' => 'setAnonymousToken',
        'token_string' => 'setTokenString',
        'entity_metatada_endpoint' => 'setEntityMetatadaEndpoint',
        'files_listing' => 'setFilesListing',
        'modification_history_listing' => 'setModificationHistoryListing',
        'notes_listing' => 'setNotesListing',
        'ownerships_listing' => 'setOwnershipsListing',
        'approvals_listing' => 'setApprovalsListing',
        'f_qcn' => 'setFQcn',
        'unique_id' => 'setUniqueId',
        'api_custom_data' => 'setApiCustomData',
        'timestamp' => 'setTimestamp',
        'deleted' => 'setDeleted',
        'taggable_type' => 'setTaggableType',
        'taggable_id' => 'setTaggableId',
        'tagging_listing' => 'setTaggingListing',
        'enabled' => 'setEnabled',
        'enabled_virtual' => 'setEnabledVirtual',
        'disabled' => 'setDisabled',
        'upload_subfolder' => 'setUploadSubfolder',
        'upload_file' => 'setUploadFile',
        'upload_file_link' => 'setUploadFileLink',
        'entity_storage_folder' => 'setEntityStorageFolder'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        '_links' => 'getLinks',
        'title' => 'getTitle',
        'description' => 'getDescription',
        'directives' => 'getDirectives',
        'serialization_groups' => 'getSerializationGroups',
        'data_processors' => 'getDataProcessors',
        'role' => 'getRole',
        'type' => 'getType',
        'notes' => 'getNotes',
        'filters' => 'getFilters',
        'data_collector_parameters' => 'getDataCollectorParameters',
        'data_collector_results' => 'getDataCollectorResults',
        'shortcode' => 'getShortcode',
        'deleted_at' => 'getDeletedAt',
        'id' => 'getId',
        'slug' => 'getSlug',
        'custom_properties' => 'getCustomProperties',
        'custom_data' => 'getCustomData',
        'created_at' => 'getCreatedAt',
        'updated_at' => 'getUpdatedAt',
        'tags' => 'getTags',
        'disabled_at' => 'getDisabledAt',
        'entity_files' => 'getEntityFiles',
        'upload_filename' => 'getUploadFilename',
        'upload_subfolder' => 'getUploadSubfolder',
        'upload_file' => 'getUploadFile',
        'upload_file_link' => 'getUploadFileLink',
        'to_string' => 'getToString',
        'directives_formatted' => 'getDirectivesFormatted',
        'directives_formatted_api' => 'getDirectivesFormattedApi',
        'parameter_names_array' => 'getParameterNamesArray',
        'parameter_operators_array' => 'getParameterOperatorsArray',
        'serialization_groups_array' => 'getSerializationGroupsArray',
        'parameter_default_values_array' => 'getParameterDefaultValuesArray',
        'parameter_types_array' => 'getParameterTypesArray',
        'result_names_array' => 'getResultNamesArray',
        'filter_names_array' => 'getFilterNamesArray',
        'data_processors_listing' => 'getDataProcessorsListing',
        'type_string' => 'getTypeString',
        'filters_listing' => 'getFiltersListing',
        'sorted_filters' => 'getSortedFilters',
        'data_collector_parameters_listing' => 'getDataCollectorParametersListing',
        'data_collector_results_listing' => 'getDataCollectorResultsListing',
        'data_processor_collectors_listing' => 'getDataProcessorCollectorsListing',
        'request_params_listing' => 'getRequestParamsListing',
        'api_shortname' => 'getApiShortname',
        'table_name' => 'getTableName',
        'full_entity_string' => 'getFullEntityString',
        'anonymous_token' => 'getAnonymousToken',
        'token_string' => 'getTokenString',
        'entity_metatada_endpoint' => 'getEntityMetatadaEndpoint',
        'files_listing' => 'getFilesListing',
        'modification_history_listing' => 'getModificationHistoryListing',
        'notes_listing' => 'getNotesListing',
        'ownerships_listing' => 'getOwnershipsListing',
        'approvals_listing' => 'getApprovalsListing',
        'f_qcn' => 'getFQcn',
        'unique_id' => 'getUniqueId',
        'api_custom_data' => 'getApiCustomData',
        'timestamp' => 'getTimestamp',
        'deleted' => 'getDeleted',
        'taggable_type' => 'getTaggableType',
        'taggable_id' => 'getTaggableId',
        'tagging_listing' => 'getTaggingListing',
        'enabled' => 'getEnabled',
        'enabled_virtual' => 'getEnabledVirtual',
        'disabled' => 'getDisabled',
        'upload_subfolder' => 'getUploadSubfolder',
        'upload_file' => 'getUploadFile',
        'upload_file_link' => 'getUploadFileLink',
        'entity_storage_folder' => 'getEntityStorageFolder'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('_links', $data ?? [], null);
        $this->setIfExists('title', $data ?? [], null);
        $this->setIfExists('description', $data ?? [], null);
        $this->setIfExists('directives', $data ?? [], null);
        $this->setIfExists('serialization_groups', $data ?? [], null);
        $this->setIfExists('data_processors', $data ?? [], null);
        $this->setIfExists('role', $data ?? [], null);
        $this->setIfExists('type', $data ?? [], null);
        $this->setIfExists('notes', $data ?? [], null);
        $this->setIfExists('filters', $data ?? [], null);
        $this->setIfExists('data_collector_parameters', $data ?? [], null);
        $this->setIfExists('data_collector_results', $data ?? [], null);
        $this->setIfExists('shortcode', $data ?? [], 'DC');
        $this->setIfExists('deleted_at', $data ?? [], null);
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('slug', $data ?? [], null);
        $this->setIfExists('custom_properties', $data ?? [], null);
        $this->setIfExists('custom_data', $data ?? [], null);
        $this->setIfExists('created_at', $data ?? [], null);
        $this->setIfExists('updated_at', $data ?? [], null);
        $this->setIfExists('tags', $data ?? [], null);
        $this->setIfExists('disabled_at', $data ?? [], null);
        $this->setIfExists('entity_files', $data ?? [], null);
        $this->setIfExists('upload_filename', $data ?? [], null);
        $this->setIfExists('upload_subfolder', $data ?? [], null);
        $this->setIfExists('upload_file', $data ?? [], null);
        $this->setIfExists('upload_file_link', $data ?? [], null);
        $this->setIfExists('to_string', $data ?? [], null);
        $this->setIfExists('directives_formatted', $data ?? [], null);
        $this->setIfExists('directives_formatted_api', $data ?? [], null);
        $this->setIfExists('parameter_names_array', $data ?? [], null);
        $this->setIfExists('parameter_operators_array', $data ?? [], null);
        $this->setIfExists('serialization_groups_array', $data ?? [], null);
        $this->setIfExists('parameter_default_values_array', $data ?? [], null);
        $this->setIfExists('parameter_types_array', $data ?? [], null);
        $this->setIfExists('result_names_array', $data ?? [], null);
        $this->setIfExists('filter_names_array', $data ?? [], null);
        $this->setIfExists('data_processors_listing', $data ?? [], null);
        $this->setIfExists('type_string', $data ?? [], null);
        $this->setIfExists('filters_listing', $data ?? [], null);
        $this->setIfExists('sorted_filters', $data ?? [], null);
        $this->setIfExists('data_collector_parameters_listing', $data ?? [], null);
        $this->setIfExists('data_collector_results_listing', $data ?? [], null);
        $this->setIfExists('data_processor_collectors_listing', $data ?? [], null);
        $this->setIfExists('request_params_listing', $data ?? [], null);
        $this->setIfExists('api_shortname', $data ?? [], null);
        $this->setIfExists('table_name', $data ?? [], null);
        $this->setIfExists('full_entity_string', $data ?? [], null);
        $this->setIfExists('anonymous_token', $data ?? [], null);
        $this->setIfExists('token_string', $data ?? [], null);
        $this->setIfExists('entity_metatada_endpoint', $data ?? [], null);
        $this->setIfExists('files_listing', $data ?? [], null);
        $this->setIfExists('modification_history_listing', $data ?? [], null);
        $this->setIfExists('notes_listing', $data ?? [], null);
        $this->setIfExists('ownerships_listing', $data ?? [], null);
        $this->setIfExists('approvals_listing', $data ?? [], null);
        $this->setIfExists('f_qcn', $data ?? [], null);
        $this->setIfExists('unique_id', $data ?? [], null);
        $this->setIfExists('api_custom_data', $data ?? [], null);
        $this->setIfExists('timestamp', $data ?? [], null);
        $this->setIfExists('deleted', $data ?? [], null);
        $this->setIfExists('taggable_type', $data ?? [], null);
        $this->setIfExists('taggable_id', $data ?? [], null);
        $this->setIfExists('tagging_listing', $data ?? [], null);
        $this->setIfExists('enabled', $data ?? [], null);
        $this->setIfExists('enabled_virtual', $data ?? [], null);
        $this->setIfExists('disabled', $data ?? [], null);
        $this->setIfExists('upload_subfolder', $data ?? [], null);
        $this->setIfExists('upload_file', $data ?? [], null);
        $this->setIfExists('upload_file_link', $data ?? [], null);
        $this->setIfExists('entity_storage_folder', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['title'] === null) {
            $invalidProperties[] = "'title' can't be null";
        }
        if ($this->container['directives'] === null) {
            $invalidProperties[] = "'directives' can't be null";
        }
        if ($this->container['role'] === null) {
            $invalidProperties[] = "'role' can't be null";
        }
        if ($this->container['slug'] === null) {
            $invalidProperties[] = "'slug' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets _links
     *
     * @return \OpenAPI\Client\Model\AccessTokenJsonhalLinks|null
     */
    public function getLinks()
    {
        return $this->container['_links'];
    }

    /**
     * Sets _links
     *
     * @param \OpenAPI\Client\Model\AccessTokenJsonhalLinks|null $_links _links
     *
     * @return self
     */
    public function setLinks($_links)
    {
        if (is_null($_links)) {
            throw new \InvalidArgumentException('non-nullable _links cannot be null');
        }
        $this->container['_links'] = $_links;

        return $this;
    }

    /**
     * Gets title
     *
     * @return string
     */
    public function getTitle()
    {
        return $this->container['title'];
    }

    /**
     * Sets title
     *
     * @param string $title title
     *
     * @return self
     */
    public function setTitle($title)
    {
        if (is_null($title)) {
            throw new \InvalidArgumentException('non-nullable title cannot be null');
        }
        $this->container['title'] = $title;

        return $this;
    }

    /**
     * Gets description
     *
     * @return string|null
     */
    public function getDescription()
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param string|null $description description
     *
     * @return self
     */
    public function setDescription($description)
    {
        if (is_null($description)) {
            array_push($this->openAPINullablesSetToNull, 'description');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('description', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets directives
     *
     * @return string
     */
    public function getDirectives()
    {
        return $this->container['directives'];
    }

    /**
     * Sets directives
     *
     * @param string $directives directives
     *
     * @return self
     */
    public function setDirectives($directives)
    {
        if (is_null($directives)) {
            throw new \InvalidArgumentException('non-nullable directives cannot be null');
        }
        $this->container['directives'] = $directives;

        return $this;
    }

    /**
     * Gets serialization_groups
     *
     * @return string|null
     */
    public function getSerializationGroups()
    {
        return $this->container['serialization_groups'];
    }

    /**
     * Sets serialization_groups
     *
     * @param string|null $serialization_groups serialization_groups
     *
     * @return self
     */
    public function setSerializationGroups($serialization_groups)
    {
        if (is_null($serialization_groups)) {
            array_push($this->openAPINullablesSetToNull, 'serialization_groups');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('serialization_groups', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['serialization_groups'] = $serialization_groups;

        return $this;
    }

    /**
     * Gets data_processors
     *
     * @return string[]|null
     */
    public function getDataProcessors()
    {
        return $this->container['data_processors'];
    }

    /**
     * Sets data_processors
     *
     * @param string[]|null $data_processors data_processors
     *
     * @return self
     */
    public function setDataProcessors($data_processors)
    {
        if (is_null($data_processors)) {
            throw new \InvalidArgumentException('non-nullable data_processors cannot be null');
        }
        $this->container['data_processors'] = $data_processors;

        return $this;
    }

    /**
     * Gets role
     *
     * @return string
     */
    public function getRole()
    {
        return $this->container['role'];
    }

    /**
     * Sets role
     *
     * @param string $role role
     *
     * @return self
     */
    public function setRole($role)
    {
        if (is_null($role)) {
            throw new \InvalidArgumentException('non-nullable role cannot be null');
        }
        $this->container['role'] = $role;

        return $this;
    }

    /**
     * Gets type
     *
     * @return int|null
     */
    public function getType()
    {
        return $this->container['type'];
    }

    /**
     * Sets type
     *
     * @param int|null $type type
     *
     * @return self
     */
    public function setType($type)
    {
        if (is_null($type)) {
            throw new \InvalidArgumentException('non-nullable type cannot be null');
        }
        $this->container['type'] = $type;

        return $this;
    }

    /**
     * Gets notes
     *
     * @return string|null
     */
    public function getNotes()
    {
        return $this->container['notes'];
    }

    /**
     * Sets notes
     *
     * @param string|null $notes notes
     *
     * @return self
     */
    public function setNotes($notes)
    {
        if (is_null($notes)) {
            array_push($this->openAPINullablesSetToNull, 'notes');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('notes', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['notes'] = $notes;

        return $this;
    }

    /**
     * Gets filters
     *
     * @return string[]|null
     */
    public function getFilters()
    {
        return $this->container['filters'];
    }

    /**
     * Sets filters
     *
     * @param string[]|null $filters filters
     *
     * @return self
     */
    public function setFilters($filters)
    {
        if (is_null($filters)) {
            throw new \InvalidArgumentException('non-nullable filters cannot be null');
        }
        $this->container['filters'] = $filters;

        return $this;
    }

    /**
     * Gets data_collector_parameters
     *
     * @return string[]|null
     */
    public function getDataCollectorParameters()
    {
        return $this->container['data_collector_parameters'];
    }

    /**
     * Sets data_collector_parameters
     *
     * @param string[]|null $data_collector_parameters data_collector_parameters
     *
     * @return self
     */
    public function setDataCollectorParameters($data_collector_parameters)
    {
        if (is_null($data_collector_parameters)) {
            throw new \InvalidArgumentException('non-nullable data_collector_parameters cannot be null');
        }
        $this->container['data_collector_parameters'] = $data_collector_parameters;

        return $this;
    }

    /**
     * Gets data_collector_results
     *
     * @return string[]|null
     */
    public function getDataCollectorResults()
    {
        return $this->container['data_collector_results'];
    }

    /**
     * Sets data_collector_results
     *
     * @param string[]|null $data_collector_results data_collector_results
     *
     * @return self
     */
    public function setDataCollectorResults($data_collector_results)
    {
        if (is_null($data_collector_results)) {
            throw new \InvalidArgumentException('non-nullable data_collector_results cannot be null');
        }
        $this->container['data_collector_results'] = $data_collector_results;

        return $this;
    }

    /**
     * Gets shortcode
     *
     * @return string|null
     */
    public function getShortcode()
    {
        return $this->container['shortcode'];
    }

    /**
     * Sets shortcode
     *
     * @param string|null $shortcode shortcode
     *
     * @return self
     */
    public function setShortcode($shortcode)
    {
        if (is_null($shortcode)) {
            throw new \InvalidArgumentException('non-nullable shortcode cannot be null');
        }
        $this->container['shortcode'] = $shortcode;

        return $this;
    }

    /**
     * Gets deleted_at
     *
     * @return \DateTime|null
     */
    public function getDeletedAt()
    {
        return $this->container['deleted_at'];
    }

    /**
     * Sets deleted_at
     *
     * @param \DateTime|null $deleted_at deleted_at
     *
     * @return self
     */
    public function setDeletedAt($deleted_at)
    {
        if (is_null($deleted_at)) {
            array_push($this->openAPINullablesSetToNull, 'deleted_at');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('deleted_at', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['deleted_at'] = $deleted_at;

        return $this;
    }

    /**
     * Gets id
     *
     * @return int|null
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param int|null $id DB Identifier
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets slug
     *
     * @return string
     */
    public function getSlug()
    {
        return $this->container['slug'];
    }

    /**
     * Sets slug
     *
     * @param string $slug DB Identifier
     *
     * @return self
     */
    public function setSlug($slug)
    {
        if (is_null($slug)) {
            throw new \InvalidArgumentException('non-nullable slug cannot be null');
        }
        $this->container['slug'] = $slug;

        return $this;
    }

    /**
     * Gets custom_properties
     *
     * @return mixed|null
     */
    public function getCustomProperties()
    {
        return $this->container['custom_properties'];
    }

    /**
     * Sets custom_properties
     *
     * @param mixed|null $custom_properties custom_properties
     *
     * @return self
     */
    public function setCustomProperties($custom_properties)
    {
        if (is_null($custom_properties)) {
            array_push($this->openAPINullablesSetToNull, 'custom_properties');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('custom_properties', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['custom_properties'] = $custom_properties;

        return $this;
    }

    /**
     * Gets custom_data
     *
     * @return string[]|null
     */
    public function getCustomData()
    {
        return $this->container['custom_data'];
    }

    /**
     * Sets custom_data
     *
     * @param string[]|null $custom_data custom_data
     *
     * @return self
     */
    public function setCustomData($custom_data)
    {
        if (is_null($custom_data)) {
            array_push($this->openAPINullablesSetToNull, 'custom_data');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('custom_data', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['custom_data'] = $custom_data;

        return $this;
    }

    /**
     * Gets created_at
     *
     * @return \DateTime|null
     */
    public function getCreatedAt()
    {
        return $this->container['created_at'];
    }

    /**
     * Sets created_at
     *
     * @param \DateTime|null $created_at created_at
     *
     * @return self
     */
    public function setCreatedAt($created_at)
    {
        if (is_null($created_at)) {
            throw new \InvalidArgumentException('non-nullable created_at cannot be null');
        }
        $this->container['created_at'] = $created_at;

        return $this;
    }

    /**
     * Gets updated_at
     *
     * @return \DateTime|null
     */
    public function getUpdatedAt()
    {
        return $this->container['updated_at'];
    }

    /**
     * Sets updated_at
     *
     * @param \DateTime|null $updated_at updated_at
     *
     * @return self
     */
    public function setUpdatedAt($updated_at)
    {
        if (is_null($updated_at)) {
            throw new \InvalidArgumentException('non-nullable updated_at cannot be null');
        }
        $this->container['updated_at'] = $updated_at;

        return $this;
    }

    /**
     * Gets tags
     *
     * @return string[]|null
     */
    public function getTags()
    {
        return $this->container['tags'];
    }

    /**
     * Sets tags
     *
     * @param string[]|null $tags tags
     *
     * @return self
     */
    public function setTags($tags)
    {
        if (is_null($tags)) {
            throw new \InvalidArgumentException('non-nullable tags cannot be null');
        }
        $this->container['tags'] = $tags;

        return $this;
    }

    /**
     * Gets disabled_at
     *
     * @return \DateTime|null
     */
    public function getDisabledAt()
    {
        return $this->container['disabled_at'];
    }

    /**
     * Sets disabled_at
     *
     * @param \DateTime|null $disabled_at disabled_at
     *
     * @return self
     */
    public function setDisabledAt($disabled_at)
    {
        if (is_null($disabled_at)) {
            array_push($this->openAPINullablesSetToNull, 'disabled_at');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('disabled_at', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['disabled_at'] = $disabled_at;

        return $this;
    }

    /**
     * Gets entity_files
     *
     * @return \OpenAPI\Client\Model\CollectionJsonhal|null
     */
    public function getEntityFiles()
    {
        return $this->container['entity_files'];
    }

    /**
     * Sets entity_files
     *
     * @param \OpenAPI\Client\Model\CollectionJsonhal|null $entity_files entity_files
     *
     * @return self
     */
    public function setEntityFiles($entity_files)
    {
        if (is_null($entity_files)) {
            throw new \InvalidArgumentException('non-nullable entity_files cannot be null');
        }
        $this->container['entity_files'] = $entity_files;

        return $this;
    }

    /**
     * Gets upload_filename
     *
     * @return string|null
     */
    public function getUploadFilename()
    {
        return $this->container['upload_filename'];
    }

    /**
     * Sets upload_filename
     *
     * @param string|null $upload_filename upload_filename
     *
     * @return self
     */
    public function setUploadFilename($upload_filename)
    {
        if (is_null($upload_filename)) {
            throw new \InvalidArgumentException('non-nullable upload_filename cannot be null');
        }
        $this->container['upload_filename'] = $upload_filename;

        return $this;
    }

    /**
     * Gets upload_subfolder
     *
     * @return string|null
     */
    public function getUploadSubfolder()
    {
        return $this->container['upload_subfolder'];
    }

    /**
     * Sets upload_subfolder
     *
     * @param string|null $upload_subfolder upload_subfolder
     *
     * @return self
     */
    public function setUploadSubfolder($upload_subfolder)
    {
        if (is_null($upload_subfolder)) {
            throw new \InvalidArgumentException('non-nullable upload_subfolder cannot be null');
        }
        $this->container['upload_subfolder'] = $upload_subfolder;

        return $this;
    }

    /**
     * Gets upload_file
     *
     * @return string|null
     */
    public function getUploadFile()
    {
        return $this->container['upload_file'];
    }

    /**
     * Sets upload_file
     *
     * @param string|null $upload_file upload_file
     *
     * @return self
     */
    public function setUploadFile($upload_file)
    {
        if (is_null($upload_file)) {
            throw new \InvalidArgumentException('non-nullable upload_file cannot be null');
        }
        $this->container['upload_file'] = $upload_file;

        return $this;
    }

    /**
     * Gets upload_file_link
     *
     * @return string|null
     */
    public function getUploadFileLink()
    {
        return $this->container['upload_file_link'];
    }

    /**
     * Sets upload_file_link
     *
     * @param string|null $upload_file_link upload_file_link
     *
     * @return self
     */
    public function setUploadFileLink($upload_file_link)
    {
        if (is_null($upload_file_link)) {
            throw new \InvalidArgumentException('non-nullable upload_file_link cannot be null');
        }
        $this->container['upload_file_link'] = $upload_file_link;

        return $this;
    }

    /**
     * Gets to_string
     *
     * @return string|null
     */
    public function getToString()
    {
        return $this->container['to_string'];
    }

    /**
     * Sets to_string
     *
     * @param string|null $to_string to_string
     *
     * @return self
     */
    public function setToString($to_string)
    {
        if (is_null($to_string)) {
            throw new \InvalidArgumentException('non-nullable to_string cannot be null');
        }
        $this->container['to_string'] = $to_string;

        return $this;
    }

    /**
     * Gets directives_formatted
     *
     * @return string|null
     */
    public function getDirectivesFormatted()
    {
        return $this->container['directives_formatted'];
    }

    /**
     * Sets directives_formatted
     *
     * @param string|null $directives_formatted directives_formatted
     *
     * @return self
     */
    public function setDirectivesFormatted($directives_formatted)
    {
        if (is_null($directives_formatted)) {
            throw new \InvalidArgumentException('non-nullable directives_formatted cannot be null');
        }
        $this->container['directives_formatted'] = $directives_formatted;

        return $this;
    }

    /**
     * Gets directives_formatted_api
     *
     * @return string|null
     */
    public function getDirectivesFormattedApi()
    {
        return $this->container['directives_formatted_api'];
    }

    /**
     * Sets directives_formatted_api
     *
     * @param string|null $directives_formatted_api directives_formatted_api
     *
     * @return self
     */
    public function setDirectivesFormattedApi($directives_formatted_api)
    {
        if (is_null($directives_formatted_api)) {
            throw new \InvalidArgumentException('non-nullable directives_formatted_api cannot be null');
        }
        $this->container['directives_formatted_api'] = $directives_formatted_api;

        return $this;
    }

    /**
     * Gets parameter_names_array
     *
     * @return string[]|null
     */
    public function getParameterNamesArray()
    {
        return $this->container['parameter_names_array'];
    }

    /**
     * Sets parameter_names_array
     *
     * @param string[]|null $parameter_names_array parameter_names_array
     *
     * @return self
     */
    public function setParameterNamesArray($parameter_names_array)
    {
        if (is_null($parameter_names_array)) {
            throw new \InvalidArgumentException('non-nullable parameter_names_array cannot be null');
        }
        $this->container['parameter_names_array'] = $parameter_names_array;

        return $this;
    }

    /**
     * Gets parameter_operators_array
     *
     * @return string[]|null
     */
    public function getParameterOperatorsArray()
    {
        return $this->container['parameter_operators_array'];
    }

    /**
     * Sets parameter_operators_array
     *
     * @param string[]|null $parameter_operators_array parameter_operators_array
     *
     * @return self
     */
    public function setParameterOperatorsArray($parameter_operators_array)
    {
        if (is_null($parameter_operators_array)) {
            throw new \InvalidArgumentException('non-nullable parameter_operators_array cannot be null');
        }
        $this->container['parameter_operators_array'] = $parameter_operators_array;

        return $this;
    }

    /**
     * Gets serialization_groups_array
     *
     * @return string[]|null
     */
    public function getSerializationGroupsArray()
    {
        return $this->container['serialization_groups_array'];
    }

    /**
     * Sets serialization_groups_array
     *
     * @param string[]|null $serialization_groups_array serialization_groups_array
     *
     * @return self
     */
    public function setSerializationGroupsArray($serialization_groups_array)
    {
        if (is_null($serialization_groups_array)) {
            throw new \InvalidArgumentException('non-nullable serialization_groups_array cannot be null');
        }
        $this->container['serialization_groups_array'] = $serialization_groups_array;

        return $this;
    }

    /**
     * Gets parameter_default_values_array
     *
     * @return string[]|null
     */
    public function getParameterDefaultValuesArray()
    {
        return $this->container['parameter_default_values_array'];
    }

    /**
     * Sets parameter_default_values_array
     *
     * @param string[]|null $parameter_default_values_array parameter_default_values_array
     *
     * @return self
     */
    public function setParameterDefaultValuesArray($parameter_default_values_array)
    {
        if (is_null($parameter_default_values_array)) {
            throw new \InvalidArgumentException('non-nullable parameter_default_values_array cannot be null');
        }
        $this->container['parameter_default_values_array'] = $parameter_default_values_array;

        return $this;
    }

    /**
     * Gets parameter_types_array
     *
     * @return string[]|null
     */
    public function getParameterTypesArray()
    {
        return $this->container['parameter_types_array'];
    }

    /**
     * Sets parameter_types_array
     *
     * @param string[]|null $parameter_types_array parameter_types_array
     *
     * @return self
     */
    public function setParameterTypesArray($parameter_types_array)
    {
        if (is_null($parameter_types_array)) {
            throw new \InvalidArgumentException('non-nullable parameter_types_array cannot be null');
        }
        $this->container['parameter_types_array'] = $parameter_types_array;

        return $this;
    }

    /**
     * Gets result_names_array
     *
     * @return string[]|null
     */
    public function getResultNamesArray()
    {
        return $this->container['result_names_array'];
    }

    /**
     * Sets result_names_array
     *
     * @param string[]|null $result_names_array result_names_array
     *
     * @return self
     */
    public function setResultNamesArray($result_names_array)
    {
        if (is_null($result_names_array)) {
            throw new \InvalidArgumentException('non-nullable result_names_array cannot be null');
        }
        $this->container['result_names_array'] = $result_names_array;

        return $this;
    }

    /**
     * Gets filter_names_array
     *
     * @return string[]|null
     */
    public function getFilterNamesArray()
    {
        return $this->container['filter_names_array'];
    }

    /**
     * Sets filter_names_array
     *
     * @param string[]|null $filter_names_array filter_names_array
     *
     * @return self
     */
    public function setFilterNamesArray($filter_names_array)
    {
        if (is_null($filter_names_array)) {
            throw new \InvalidArgumentException('non-nullable filter_names_array cannot be null');
        }
        $this->container['filter_names_array'] = $filter_names_array;

        return $this;
    }

    /**
     * Gets data_processors_listing
     *
     * @return string|null
     */
    public function getDataProcessorsListing()
    {
        return $this->container['data_processors_listing'];
    }

    /**
     * Sets data_processors_listing
     *
     * @param string|null $data_processors_listing data_processors_listing
     *
     * @return self
     */
    public function setDataProcessorsListing($data_processors_listing)
    {
        if (is_null($data_processors_listing)) {
            throw new \InvalidArgumentException('non-nullable data_processors_listing cannot be null');
        }
        $this->container['data_processors_listing'] = $data_processors_listing;

        return $this;
    }

    /**
     * Gets type_string
     *
     * @return string|null
     */
    public function getTypeString()
    {
        return $this->container['type_string'];
    }

    /**
     * Sets type_string
     *
     * @param string|null $type_string type_string
     *
     * @return self
     */
    public function setTypeString($type_string)
    {
        if (is_null($type_string)) {
            throw new \InvalidArgumentException('non-nullable type_string cannot be null');
        }
        $this->container['type_string'] = $type_string;

        return $this;
    }

    /**
     * Gets filters_listing
     *
     * @return string|null
     */
    public function getFiltersListing()
    {
        return $this->container['filters_listing'];
    }

    /**
     * Sets filters_listing
     *
     * @param string|null $filters_listing filters_listing
     *
     * @return self
     */
    public function setFiltersListing($filters_listing)
    {
        if (is_null($filters_listing)) {
            throw new \InvalidArgumentException('non-nullable filters_listing cannot be null');
        }
        $this->container['filters_listing'] = $filters_listing;

        return $this;
    }

    /**
     * Gets sorted_filters
     *
     * @return string[]|null
     */
    public function getSortedFilters()
    {
        return $this->container['sorted_filters'];
    }

    /**
     * Sets sorted_filters
     *
     * @param string[]|null $sorted_filters sorted_filters
     *
     * @return self
     */
    public function setSortedFilters($sorted_filters)
    {
        if (is_null($sorted_filters)) {
            throw new \InvalidArgumentException('non-nullable sorted_filters cannot be null');
        }
        $this->container['sorted_filters'] = $sorted_filters;

        return $this;
    }

    /**
     * Gets data_collector_parameters_listing
     *
     * @return string|null
     */
    public function getDataCollectorParametersListing()
    {
        return $this->container['data_collector_parameters_listing'];
    }

    /**
     * Sets data_collector_parameters_listing
     *
     * @param string|null $data_collector_parameters_listing data_collector_parameters_listing
     *
     * @return self
     */
    public function setDataCollectorParametersListing($data_collector_parameters_listing)
    {
        if (is_null($data_collector_parameters_listing)) {
            throw new \InvalidArgumentException('non-nullable data_collector_parameters_listing cannot be null');
        }
        $this->container['data_collector_parameters_listing'] = $data_collector_parameters_listing;

        return $this;
    }

    /**
     * Gets data_collector_results_listing
     *
     * @return string|null
     */
    public function getDataCollectorResultsListing()
    {
        return $this->container['data_collector_results_listing'];
    }

    /**
     * Sets data_collector_results_listing
     *
     * @param string|null $data_collector_results_listing data_collector_results_listing
     *
     * @return self
     */
    public function setDataCollectorResultsListing($data_collector_results_listing)
    {
        if (is_null($data_collector_results_listing)) {
            throw new \InvalidArgumentException('non-nullable data_collector_results_listing cannot be null');
        }
        $this->container['data_collector_results_listing'] = $data_collector_results_listing;

        return $this;
    }

    /**
     * Gets data_processor_collectors_listing
     *
     * @return mixed|null
     */
    public function getDataProcessorCollectorsListing()
    {
        return $this->container['data_processor_collectors_listing'];
    }

    /**
     * Sets data_processor_collectors_listing
     *
     * @param mixed|null $data_processor_collectors_listing data_processor_collectors_listing
     *
     * @return self
     */
    public function setDataProcessorCollectorsListing($data_processor_collectors_listing)
    {
        if (is_null($data_processor_collectors_listing)) {
            array_push($this->openAPINullablesSetToNull, 'data_processor_collectors_listing');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('data_processor_collectors_listing', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['data_processor_collectors_listing'] = $data_processor_collectors_listing;

        return $this;
    }

    /**
     * Gets request_params_listing
     *
     * @return string[]|null
     */
    public function getRequestParamsListing()
    {
        return $this->container['request_params_listing'];
    }

    /**
     * Sets request_params_listing
     *
     * @param string[]|null $request_params_listing request_params_listing
     *
     * @return self
     */
    public function setRequestParamsListing($request_params_listing)
    {
        if (is_null($request_params_listing)) {
            throw new \InvalidArgumentException('non-nullable request_params_listing cannot be null');
        }
        $this->container['request_params_listing'] = $request_params_listing;

        return $this;
    }

    /**
     * Gets api_shortname
     *
     * @return string|null
     */
    public function getApiShortname()
    {
        return $this->container['api_shortname'];
    }

    /**
     * Sets api_shortname
     *
     * @param string|null $api_shortname api_shortname
     *
     * @return self
     */
    public function setApiShortname($api_shortname)
    {
        if (is_null($api_shortname)) {
            throw new \InvalidArgumentException('non-nullable api_shortname cannot be null');
        }
        $this->container['api_shortname'] = $api_shortname;

        return $this;
    }

    /**
     * Gets table_name
     *
     * @return string|null
     */
    public function getTableName()
    {
        return $this->container['table_name'];
    }

    /**
     * Sets table_name
     *
     * @param string|null $table_name table_name
     *
     * @return self
     */
    public function setTableName($table_name)
    {
        if (is_null($table_name)) {
            throw new \InvalidArgumentException('non-nullable table_name cannot be null');
        }
        $this->container['table_name'] = $table_name;

        return $this;
    }

    /**
     * Gets full_entity_string
     *
     * @return string|null
     */
    public function getFullEntityString()
    {
        return $this->container['full_entity_string'];
    }

    /**
     * Sets full_entity_string
     *
     * @param string|null $full_entity_string full_entity_string
     *
     * @return self
     */
    public function setFullEntityString($full_entity_string)
    {
        if (is_null($full_entity_string)) {
            throw new \InvalidArgumentException('non-nullable full_entity_string cannot be null');
        }
        $this->container['full_entity_string'] = $full_entity_string;

        return $this;
    }

    /**
     * Gets anonymous_token
     *
     * @return string|null
     */
    public function getAnonymousToken()
    {
        return $this->container['anonymous_token'];
    }

    /**
     * Sets anonymous_token
     *
     * @param string|null $anonymous_token anonymous_token
     *
     * @return self
     */
    public function setAnonymousToken($anonymous_token)
    {
        if (is_null($anonymous_token)) {
            throw new \InvalidArgumentException('non-nullable anonymous_token cannot be null');
        }
        $this->container['anonymous_token'] = $anonymous_token;

        return $this;
    }

    /**
     * Gets token_string
     *
     * @return string|null
     */
    public function getTokenString()
    {
        return $this->container['token_string'];
    }

    /**
     * Sets token_string
     *
     * @param string|null $token_string token_string
     *
     * @return self
     */
    public function setTokenString($token_string)
    {
        if (is_null($token_string)) {
            throw new \InvalidArgumentException('non-nullable token_string cannot be null');
        }
        $this->container['token_string'] = $token_string;

        return $this;
    }

    /**
     * Gets entity_metatada_endpoint
     *
     * @return string|null
     */
    public function getEntityMetatadaEndpoint()
    {
        return $this->container['entity_metatada_endpoint'];
    }

    /**
     * Sets entity_metatada_endpoint
     *
     * @param string|null $entity_metatada_endpoint entity_metatada_endpoint
     *
     * @return self
     */
    public function setEntityMetatadaEndpoint($entity_metatada_endpoint)
    {
        if (is_null($entity_metatada_endpoint)) {
            throw new \InvalidArgumentException('non-nullable entity_metatada_endpoint cannot be null');
        }
        $this->container['entity_metatada_endpoint'] = $entity_metatada_endpoint;

        return $this;
    }

    /**
     * Gets files_listing
     *
     * @return string|null
     */
    public function getFilesListing()
    {
        return $this->container['files_listing'];
    }

    /**
     * Sets files_listing
     *
     * @param string|null $files_listing files_listing
     *
     * @return self
     */
    public function setFilesListing($files_listing)
    {
        if (is_null($files_listing)) {
            throw new \InvalidArgumentException('non-nullable files_listing cannot be null');
        }
        $this->container['files_listing'] = $files_listing;

        return $this;
    }

    /**
     * Gets modification_history_listing
     *
     * @return string|null
     */
    public function getModificationHistoryListing()
    {
        return $this->container['modification_history_listing'];
    }

    /**
     * Sets modification_history_listing
     *
     * @param string|null $modification_history_listing modification_history_listing
     *
     * @return self
     */
    public function setModificationHistoryListing($modification_history_listing)
    {
        if (is_null($modification_history_listing)) {
            throw new \InvalidArgumentException('non-nullable modification_history_listing cannot be null');
        }
        $this->container['modification_history_listing'] = $modification_history_listing;

        return $this;
    }

    /**
     * Gets notes_listing
     *
     * @return string|null
     */
    public function getNotesListing()
    {
        return $this->container['notes_listing'];
    }

    /**
     * Sets notes_listing
     *
     * @param string|null $notes_listing notes_listing
     *
     * @return self
     */
    public function setNotesListing($notes_listing)
    {
        if (is_null($notes_listing)) {
            throw new \InvalidArgumentException('non-nullable notes_listing cannot be null');
        }
        $this->container['notes_listing'] = $notes_listing;

        return $this;
    }

    /**
     * Gets ownerships_listing
     *
     * @return string|null
     */
    public function getOwnershipsListing()
    {
        return $this->container['ownerships_listing'];
    }

    /**
     * Sets ownerships_listing
     *
     * @param string|null $ownerships_listing ownerships_listing
     *
     * @return self
     */
    public function setOwnershipsListing($ownerships_listing)
    {
        if (is_null($ownerships_listing)) {
            throw new \InvalidArgumentException('non-nullable ownerships_listing cannot be null');
        }
        $this->container['ownerships_listing'] = $ownerships_listing;

        return $this;
    }

    /**
     * Gets approvals_listing
     *
     * @return string|null
     */
    public function getApprovalsListing()
    {
        return $this->container['approvals_listing'];
    }

    /**
     * Sets approvals_listing
     *
     * @param string|null $approvals_listing approvals_listing
     *
     * @return self
     */
    public function setApprovalsListing($approvals_listing)
    {
        if (is_null($approvals_listing)) {
            throw new \InvalidArgumentException('non-nullable approvals_listing cannot be null');
        }
        $this->container['approvals_listing'] = $approvals_listing;

        return $this;
    }

    /**
     * Gets f_qcn
     *
     * @return string|null
     */
    public function getFQcn()
    {
        return $this->container['f_qcn'];
    }

    /**
     * Sets f_qcn
     *
     * @param string|null $f_qcn f_qcn
     *
     * @return self
     */
    public function setFQcn($f_qcn)
    {
        if (is_null($f_qcn)) {
            throw new \InvalidArgumentException('non-nullable f_qcn cannot be null');
        }
        $this->container['f_qcn'] = $f_qcn;

        return $this;
    }

    /**
     * Gets unique_id
     *
     * @return string|null
     */
    public function getUniqueId()
    {
        return $this->container['unique_id'];
    }

    /**
     * Sets unique_id
     *
     * @param string|null $unique_id unique_id
     *
     * @return self
     */
    public function setUniqueId($unique_id)
    {
        if (is_null($unique_id)) {
            throw new \InvalidArgumentException('non-nullable unique_id cannot be null');
        }
        $this->container['unique_id'] = $unique_id;

        return $this;
    }

    /**
     * Gets api_custom_data
     *
     * @return mixed|null
     */
    public function getApiCustomData()
    {
        return $this->container['api_custom_data'];
    }

    /**
     * Sets api_custom_data
     *
     * @param mixed|null $api_custom_data api_custom_data
     *
     * @return self
     */
    public function setApiCustomData($api_custom_data)
    {
        if (is_null($api_custom_data)) {
            array_push($this->openAPINullablesSetToNull, 'api_custom_data');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('api_custom_data', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['api_custom_data'] = $api_custom_data;

        return $this;
    }

    /**
     * Gets timestamp
     *
     * @return \DateTime|null
     */
    public function getTimestamp()
    {
        return $this->container['timestamp'];
    }

    /**
     * Sets timestamp
     *
     * @param \DateTime|null $timestamp Get createdAt.
     *
     * @return self
     */
    public function setTimestamp($timestamp)
    {
        if (is_null($timestamp)) {
            throw new \InvalidArgumentException('non-nullable timestamp cannot be null');
        }
        $this->container['timestamp'] = $timestamp;

        return $this;
    }

    /**
     * Gets deleted
     *
     * @return bool|null
     */
    public function getDeleted()
    {
        return $this->container['deleted'];
    }

    /**
     * Sets deleted
     *
     * @param bool|null $deleted Check if the entity has been soft deleted.
     *
     * @return self
     */
    public function setDeleted($deleted)
    {
        if (is_null($deleted)) {
            throw new \InvalidArgumentException('non-nullable deleted cannot be null');
        }
        $this->container['deleted'] = $deleted;

        return $this;
    }

    /**
     * Gets taggable_type
     *
     * @return string|null
     */
    public function getTaggableType()
    {
        return $this->container['taggable_type'];
    }

    /**
     * Sets taggable_type
     *
     * @param string|null $taggable_type taggable_type
     *
     * @return self
     */
    public function setTaggableType($taggable_type)
    {
        if (is_null($taggable_type)) {
            array_push($this->openAPINullablesSetToNull, 'taggable_type');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('taggable_type', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['taggable_type'] = $taggable_type;

        return $this;
    }

    /**
     * Gets taggable_id
     *
     * @return int|null
     */
    public function getTaggableId()
    {
        return $this->container['taggable_id'];
    }

    /**
     * Sets taggable_id
     *
     * @param int|null $taggable_id taggable_id
     *
     * @return self
     */
    public function setTaggableId($taggable_id)
    {
        if (is_null($taggable_id)) {
            throw new \InvalidArgumentException('non-nullable taggable_id cannot be null');
        }
        $this->container['taggable_id'] = $taggable_id;

        return $this;
    }

    /**
     * Gets tagging_listing
     *
     * @return string|null
     */
    public function getTaggingListing()
    {
        return $this->container['tagging_listing'];
    }

    /**
     * Sets tagging_listing
     *
     * @param string|null $tagging_listing Get Tagging Listing Why this crashes get annotations (proxy class?)
     *
     * @return self
     */
    public function setTaggingListing($tagging_listing)
    {
        if (is_null($tagging_listing)) {
            throw new \InvalidArgumentException('non-nullable tagging_listing cannot be null');
        }
        $this->container['tagging_listing'] = $tagging_listing;

        return $this;
    }

    /**
     * Gets enabled
     *
     * @return bool|null
     */
    public function getEnabled()
    {
        return $this->container['enabled'];
    }

    /**
     * Sets enabled
     *
     * @param bool|null $enabled Check if the entity is enabled.
     *
     * @return self
     */
    public function setEnabled($enabled)
    {
        if (is_null($enabled)) {
            throw new \InvalidArgumentException('non-nullable enabled cannot be null');
        }
        $this->container['enabled'] = $enabled;

        return $this;
    }

    /**
     * Gets enabled_virtual
     *
     * @return bool|null
     */
    public function getEnabledVirtual()
    {
        return $this->container['enabled_virtual'];
    }

    /**
     * Sets enabled_virtual
     *
     * @param bool|null $enabled_virtual Virtual isEnabled property.
     *
     * @return self
     */
    public function setEnabledVirtual($enabled_virtual)
    {
        if (is_null($enabled_virtual)) {
            throw new \InvalidArgumentException('non-nullable enabled_virtual cannot be null');
        }
        $this->container['enabled_virtual'] = $enabled_virtual;

        return $this;
    }

    /**
     * Gets disabled
     *
     * @return bool|null
     */
    public function getDisabled()
    {
        return $this->container['disabled'];
    }

    /**
     * Sets disabled
     *
     * @param bool|null $disabled Check if the entit is enabled.
     *
     * @return self
     */
    public function setDisabled($disabled)
    {
        if (is_null($disabled)) {
            throw new \InvalidArgumentException('non-nullable disabled cannot be null');
        }
        $this->container['disabled'] = $disabled;

        return $this;
    }

    /**
     * Gets upload_subfolder
     *
     * @return string|null
     */
    public function getUploadSubfolder()
    {
        return $this->container['upload_subfolder'];
    }

    /**
     * Sets upload_subfolder
     *
     * @param string|null $upload_subfolder upload_subfolder
     *
     * @return self
     */
    public function setUploadSubfolder($upload_subfolder)
    {
        if (is_null($upload_subfolder)) {
            throw new \InvalidArgumentException('non-nullable upload_subfolder cannot be null');
        }
        $this->container['upload_subfolder'] = $upload_subfolder;

        return $this;
    }

    /**
     * Gets upload_file
     *
     * @return string|null
     */
    public function getUploadFile()
    {
        return $this->container['upload_file'];
    }

    /**
     * Sets upload_file
     *
     * @param string|null $upload_file upload_file
     *
     * @return self
     */
    public function setUploadFile($upload_file)
    {
        if (is_null($upload_file)) {
            throw new \InvalidArgumentException('non-nullable upload_file cannot be null');
        }
        $this->container['upload_file'] = $upload_file;

        return $this;
    }

    /**
     * Gets upload_file_link
     *
     * @return string|null
     */
    public function getUploadFileLink()
    {
        return $this->container['upload_file_link'];
    }

    /**
     * Sets upload_file_link
     *
     * @param string|null $upload_file_link upload_file_link
     *
     * @return self
     */
    public function setUploadFileLink($upload_file_link)
    {
        if (is_null($upload_file_link)) {
            throw new \InvalidArgumentException('non-nullable upload_file_link cannot be null');
        }
        $this->container['upload_file_link'] = $upload_file_link;

        return $this;
    }

    /**
     * Gets entity_storage_folder
     *
     * @return string|null
     */
    public function getEntityStorageFolder()
    {
        return $this->container['entity_storage_folder'];
    }

    /**
     * Sets entity_storage_folder
     *
     * @param string|null $entity_storage_folder entity_storage_folder
     *
     * @return self
     */
    public function setEntityStorageFolder($entity_storage_folder)
    {
        if (is_null($entity_storage_folder)) {
            throw new \InvalidArgumentException('non-nullable entity_storage_folder cannot be null');
        }
        $this->container['entity_storage_folder'] = $entity_storage_folder;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


