<?php
/**
 * PayrollLinetypesJsonldIdStandardMetadataPayrollLineTypeMetadataTagTaggingListPayrollLineTypeRelationsTimestampable
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PHPR API
 *
 * PHPR API USING API-PLATFORM
 *
 * The version of the OpenAPI document: 3.7.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.18.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * PayrollLinetypesJsonldIdStandardMetadataPayrollLineTypeMetadataTagTaggingListPayrollLineTypeRelationsTimestampable Class Doc Comment
 *
 * @category Class
 * @description LineType.
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class PayrollLinetypesJsonldIdStandardMetadataPayrollLineTypeMetadataTagTaggingListPayrollLineTypeRelationsTimestampable implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'payroll_linetypes.jsonld-id_standardMetadata_payrollLineTypeMetadata_tagTaggingList_payrollLineTypeRelations_timestampable';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'at_context' => '\OpenAPI\Client\Model\AsyncRequestInputAsyncRequestOutputJsonldContext',
        'at_id' => 'string',
        'at_type' => 'string',
        'shortcode' => 'string',
        'id' => 'int',
        'slug' => 'string',
        'created_at' => '\DateTime',
        'updated_at' => '\DateTime',
        'custom_properties_listing' => 'string',
        'api_shortname' => 'string',
        'translation_title_property_name' => 'string',
        'anonymous_token' => 'string',
        'entity_metatada_endpoint' => 'string',
        'f_qcn' => 'string',
        'unique_id' => 'string',
        'tagging_listing' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'at_context' => null,
        'at_id' => null,
        'at_type' => null,
        'shortcode' => null,
        'id' => null,
        'slug' => null,
        'created_at' => 'date-time',
        'updated_at' => 'date-time',
        'custom_properties_listing' => null,
        'api_shortname' => null,
        'translation_title_property_name' => null,
        'anonymous_token' => null,
        'entity_metatada_endpoint' => null,
        'f_qcn' => null,
        'unique_id' => null,
        'tagging_listing' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'at_context' => false,
        'at_id' => false,
        'at_type' => false,
        'shortcode' => false,
        'id' => false,
        'slug' => false,
        'created_at' => false,
        'updated_at' => false,
        'custom_properties_listing' => false,
        'api_shortname' => false,
        'translation_title_property_name' => true,
        'anonymous_token' => false,
        'entity_metatada_endpoint' => false,
        'f_qcn' => false,
        'unique_id' => false,
        'tagging_listing' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'at_context' => '@context',
        'at_id' => '@id',
        'at_type' => '@type',
        'shortcode' => 'shortcode',
        'id' => 'id',
        'slug' => 'slug',
        'created_at' => 'createdAt',
        'updated_at' => 'updatedAt',
        'custom_properties_listing' => 'customPropertiesListing',
        'api_shortname' => 'apiShortname',
        'translation_title_property_name' => 'translationTitlePropertyName',
        'anonymous_token' => 'anonymousToken',
        'entity_metatada_endpoint' => 'entityMetatadaEndpoint',
        'f_qcn' => 'fQCN',
        'unique_id' => 'uniqueId',
        'tagging_listing' => 'taggingListing'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'at_context' => 'setAtContext',
        'at_id' => 'setAtId',
        'at_type' => 'setAtType',
        'shortcode' => 'setShortcode',
        'id' => 'setId',
        'slug' => 'setSlug',
        'created_at' => 'setCreatedAt',
        'updated_at' => 'setUpdatedAt',
        'custom_properties_listing' => 'setCustomPropertiesListing',
        'api_shortname' => 'setApiShortname',
        'translation_title_property_name' => 'setTranslationTitlePropertyName',
        'anonymous_token' => 'setAnonymousToken',
        'entity_metatada_endpoint' => 'setEntityMetatadaEndpoint',
        'f_qcn' => 'setFQcn',
        'unique_id' => 'setUniqueId',
        'tagging_listing' => 'setTaggingListing'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'at_context' => 'getAtContext',
        'at_id' => 'getAtId',
        'at_type' => 'getAtType',
        'shortcode' => 'getShortcode',
        'id' => 'getId',
        'slug' => 'getSlug',
        'created_at' => 'getCreatedAt',
        'updated_at' => 'getUpdatedAt',
        'custom_properties_listing' => 'getCustomPropertiesListing',
        'api_shortname' => 'getApiShortname',
        'translation_title_property_name' => 'getTranslationTitlePropertyName',
        'anonymous_token' => 'getAnonymousToken',
        'entity_metatada_endpoint' => 'getEntityMetatadaEndpoint',
        'f_qcn' => 'getFQcn',
        'unique_id' => 'getUniqueId',
        'tagging_listing' => 'getTaggingListing'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('at_context', $data ?? [], null);
        $this->setIfExists('at_id', $data ?? [], null);
        $this->setIfExists('at_type', $data ?? [], null);
        $this->setIfExists('shortcode', $data ?? [], 'PLT');
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('slug', $data ?? [], null);
        $this->setIfExists('created_at', $data ?? [], null);
        $this->setIfExists('updated_at', $data ?? [], null);
        $this->setIfExists('custom_properties_listing', $data ?? [], null);
        $this->setIfExists('api_shortname', $data ?? [], null);
        $this->setIfExists('translation_title_property_name', $data ?? [], null);
        $this->setIfExists('anonymous_token', $data ?? [], null);
        $this->setIfExists('entity_metatada_endpoint', $data ?? [], null);
        $this->setIfExists('f_qcn', $data ?? [], null);
        $this->setIfExists('unique_id', $data ?? [], null);
        $this->setIfExists('tagging_listing', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['slug'] === null) {
            $invalidProperties[] = "'slug' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets at_context
     *
     * @return \OpenAPI\Client\Model\AsyncRequestInputAsyncRequestOutputJsonldContext|null
     */
    public function getAtContext()
    {
        return $this->container['at_context'];
    }

    /**
     * Sets at_context
     *
     * @param \OpenAPI\Client\Model\AsyncRequestInputAsyncRequestOutputJsonldContext|null $at_context at_context
     *
     * @return self
     */
    public function setAtContext($at_context)
    {
        if (is_null($at_context)) {
            throw new \InvalidArgumentException('non-nullable at_context cannot be null');
        }
        $this->container['at_context'] = $at_context;

        return $this;
    }

    /**
     * Gets at_id
     *
     * @return string|null
     */
    public function getAtId()
    {
        return $this->container['at_id'];
    }

    /**
     * Sets at_id
     *
     * @param string|null $at_id at_id
     *
     * @return self
     */
    public function setAtId($at_id)
    {
        if (is_null($at_id)) {
            throw new \InvalidArgumentException('non-nullable at_id cannot be null');
        }
        $this->container['at_id'] = $at_id;

        return $this;
    }

    /**
     * Gets at_type
     *
     * @return string|null
     */
    public function getAtType()
    {
        return $this->container['at_type'];
    }

    /**
     * Sets at_type
     *
     * @param string|null $at_type at_type
     *
     * @return self
     */
    public function setAtType($at_type)
    {
        if (is_null($at_type)) {
            throw new \InvalidArgumentException('non-nullable at_type cannot be null');
        }
        $this->container['at_type'] = $at_type;

        return $this;
    }

    /**
     * Gets shortcode
     *
     * @return string|null
     */
    public function getShortcode()
    {
        return $this->container['shortcode'];
    }

    /**
     * Sets shortcode
     *
     * @param string|null $shortcode shortcode
     *
     * @return self
     */
    public function setShortcode($shortcode)
    {
        if (is_null($shortcode)) {
            throw new \InvalidArgumentException('non-nullable shortcode cannot be null');
        }
        $this->container['shortcode'] = $shortcode;

        return $this;
    }

    /**
     * Gets id
     *
     * @return int|null
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param int|null $id DB Identifier
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets slug
     *
     * @return string
     */
    public function getSlug()
    {
        return $this->container['slug'];
    }

    /**
     * Sets slug
     *
     * @param string $slug DB Identifier
     *
     * @return self
     */
    public function setSlug($slug)
    {
        if (is_null($slug)) {
            throw new \InvalidArgumentException('non-nullable slug cannot be null');
        }
        $this->container['slug'] = $slug;

        return $this;
    }

    /**
     * Gets created_at
     *
     * @return \DateTime|null
     */
    public function getCreatedAt()
    {
        return $this->container['created_at'];
    }

    /**
     * Sets created_at
     *
     * @param \DateTime|null $created_at created_at
     *
     * @return self
     */
    public function setCreatedAt($created_at)
    {
        if (is_null($created_at)) {
            throw new \InvalidArgumentException('non-nullable created_at cannot be null');
        }
        $this->container['created_at'] = $created_at;

        return $this;
    }

    /**
     * Gets updated_at
     *
     * @return \DateTime|null
     */
    public function getUpdatedAt()
    {
        return $this->container['updated_at'];
    }

    /**
     * Sets updated_at
     *
     * @param \DateTime|null $updated_at updated_at
     *
     * @return self
     */
    public function setUpdatedAt($updated_at)
    {
        if (is_null($updated_at)) {
            throw new \InvalidArgumentException('non-nullable updated_at cannot be null');
        }
        $this->container['updated_at'] = $updated_at;

        return $this;
    }

    /**
     * Gets custom_properties_listing
     *
     * @return string|null
     */
    public function getCustomPropertiesListing()
    {
        return $this->container['custom_properties_listing'];
    }

    /**
     * Sets custom_properties_listing
     *
     * @param string|null $custom_properties_listing custom_properties_listing
     *
     * @return self
     */
    public function setCustomPropertiesListing($custom_properties_listing)
    {
        if (is_null($custom_properties_listing)) {
            throw new \InvalidArgumentException('non-nullable custom_properties_listing cannot be null');
        }
        $this->container['custom_properties_listing'] = $custom_properties_listing;

        return $this;
    }

    /**
     * Gets api_shortname
     *
     * @return string|null
     */
    public function getApiShortname()
    {
        return $this->container['api_shortname'];
    }

    /**
     * Sets api_shortname
     *
     * @param string|null $api_shortname api_shortname
     *
     * @return self
     */
    public function setApiShortname($api_shortname)
    {
        if (is_null($api_shortname)) {
            throw new \InvalidArgumentException('non-nullable api_shortname cannot be null');
        }
        $this->container['api_shortname'] = $api_shortname;

        return $this;
    }

    /**
     * Gets translation_title_property_name
     *
     * @return string|null
     */
    public function getTranslationTitlePropertyName()
    {
        return $this->container['translation_title_property_name'];
    }

    /**
     * Sets translation_title_property_name
     *
     * @param string|null $translation_title_property_name translation_title_property_name
     *
     * @return self
     */
    public function setTranslationTitlePropertyName($translation_title_property_name)
    {
        if (is_null($translation_title_property_name)) {
            array_push($this->openAPINullablesSetToNull, 'translation_title_property_name');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('translation_title_property_name', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['translation_title_property_name'] = $translation_title_property_name;

        return $this;
    }

    /**
     * Gets anonymous_token
     *
     * @return string|null
     */
    public function getAnonymousToken()
    {
        return $this->container['anonymous_token'];
    }

    /**
     * Sets anonymous_token
     *
     * @param string|null $anonymous_token anonymous_token
     *
     * @return self
     */
    public function setAnonymousToken($anonymous_token)
    {
        if (is_null($anonymous_token)) {
            throw new \InvalidArgumentException('non-nullable anonymous_token cannot be null');
        }
        $this->container['anonymous_token'] = $anonymous_token;

        return $this;
    }

    /**
     * Gets entity_metatada_endpoint
     *
     * @return string|null
     */
    public function getEntityMetatadaEndpoint()
    {
        return $this->container['entity_metatada_endpoint'];
    }

    /**
     * Sets entity_metatada_endpoint
     *
     * @param string|null $entity_metatada_endpoint entity_metatada_endpoint
     *
     * @return self
     */
    public function setEntityMetatadaEndpoint($entity_metatada_endpoint)
    {
        if (is_null($entity_metatada_endpoint)) {
            throw new \InvalidArgumentException('non-nullable entity_metatada_endpoint cannot be null');
        }
        $this->container['entity_metatada_endpoint'] = $entity_metatada_endpoint;

        return $this;
    }

    /**
     * Gets f_qcn
     *
     * @return string|null
     */
    public function getFQcn()
    {
        return $this->container['f_qcn'];
    }

    /**
     * Sets f_qcn
     *
     * @param string|null $f_qcn f_qcn
     *
     * @return self
     */
    public function setFQcn($f_qcn)
    {
        if (is_null($f_qcn)) {
            throw new \InvalidArgumentException('non-nullable f_qcn cannot be null');
        }
        $this->container['f_qcn'] = $f_qcn;

        return $this;
    }

    /**
     * Gets unique_id
     *
     * @return string|null
     */
    public function getUniqueId()
    {
        return $this->container['unique_id'];
    }

    /**
     * Sets unique_id
     *
     * @param string|null $unique_id unique_id
     *
     * @return self
     */
    public function setUniqueId($unique_id)
    {
        if (is_null($unique_id)) {
            throw new \InvalidArgumentException('non-nullable unique_id cannot be null');
        }
        $this->container['unique_id'] = $unique_id;

        return $this;
    }

    /**
     * Gets tagging_listing
     *
     * @return string|null
     */
    public function getTaggingListing()
    {
        return $this->container['tagging_listing'];
    }

    /**
     * Sets tagging_listing
     *
     * @param string|null $tagging_listing Get Tagging Listing Why this crashes get annotations (proxy class?)
     *
     * @return self
     */
    public function setTaggingListing($tagging_listing)
    {
        if (is_null($tagging_listing)) {
            throw new \InvalidArgumentException('non-nullable tagging_listing cannot be null');
        }
        $this->container['tagging_listing'] = $tagging_listing;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


