<?php
/**
 * PayrollT4s
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PHPR API
 *
 * PHPR API USING API-PLATFORM
 *
 * The version of the OpenAPI document: 3.7.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.18.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * PayrollT4s Class Doc Comment
 *
 * @category Class
 * @description T4s.
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class PayrollT4s implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'payroll_t4s';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'created_date' => '\DateTime',
        'date_start' => '\DateTime',
        'date_end' => '\DateTime',
        'employee' => 'string',
        'nb_hours' => 'string',
        'holiday_nb_hours' => 'string',
        'nb_employee' => 'int',
        'employee_hour_salary' => 'string',
        'vacancy_paid' => 'string',
        'vacancy_amount' => 'string',
        'employee_vacancy' => 'string',
        'bonus' => 'string',
        'gross_salary' => 'string',
        'employee_assemp' => 'string',
        'employee_rrq' => 'string',
        'employee_rqap' => 'string',
        'employee_rpc' => 'string',
        'employee_impot_fed' => 'string',
        'employee_impot_prov' => 'string',
        'employee_taxable_benefits' => 'string',
        'voluntary_retirement_savings_plan' => 'string',
        'registered_retirement_savings_plan' => 'string',
        'tax_free_saving_account' => 'string',
        'employer_assemp' => 'string',
        'employer_rrq' => 'string',
        'employer_rqap' => 'string',
        'employer_rpc' => 'string',
        'employer_fss' => 'string',
        'employer_csst' => 'string',
        'allowance_total' => 'string',
        'net_salary' => 'string',
        'payrolls' => 'string[]',
        'payroll' => 'string',
        'notes' => 'string',
        'owning_corporation' => 'string',
        'shortcode' => 'string',
        'deleted_at' => '\DateTime',
        'id' => 'int',
        'slug' => 'string',
        'custom_properties' => 'mixed',
        'custom_data' => 'string[]',
        'created_at' => '\DateTime',
        'updated_at' => '\DateTime',
        'tags' => 'string[]',
        'disabled_at' => '\DateTime',
        'entity_files' => '\OpenAPI\Client\Model\Collection',
        'upload_filename' => 'string',
        'upload_subfolder' => 'string',
        'upload_file' => 'string',
        'upload_file_link' => 'string',
        'payroll_employees' => 'string[]',
        'payroll_listing' => 'string',
        'allowances' => 'string[]',
        'timesheets' => 'string[]',
        'timesheets_listing' => 'string',
        'bonis' => 'string[]',
        'to_string' => 'string',
        'total_employee_das_amount' => 'float',
        'total_employer_das_amount' => 'float',
        'total_provincial' => 'float',
        'total_federal' => 'float',
        'employe_saving_taxable_reduction' => 'float',
        'custom_properties_listing' => 'string',
        'api_shortname' => 'string',
        'table_name' => 'string',
        'full_entity_string' => 'string',
        'anonymous_token' => 'string',
        'token_string' => 'string',
        'entity_metatada_endpoint' => 'string',
        'files_listing' => 'string',
        'modification_history_listing' => 'string',
        'notes_listing' => 'string',
        'ownerships_listing' => 'string',
        'approvals_listing' => 'string',
        'f_qcn' => 'string',
        'unique_id' => 'string',
        'api_custom_data' => 'mixed',
        'timestamp' => '\DateTime',
        'deleted' => 'bool',
        'taggable_type' => 'string',
        'taggable_id' => 'int',
        'tagging_listing' => 'string',
        'enabled' => 'bool',
        'enabled_virtual' => 'bool',
        'disabled' => 'bool',
        'upload_subfolder' => 'string',
        'upload_file' => 'string',
        'upload_file_link' => 'string',
        'entity_storage_folder' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'created_date' => 'date-time',
        'date_start' => 'date-time',
        'date_end' => 'date-time',
        'employee' => 'iri-reference',
        'nb_hours' => null,
        'holiday_nb_hours' => null,
        'nb_employee' => null,
        'employee_hour_salary' => null,
        'vacancy_paid' => null,
        'vacancy_amount' => null,
        'employee_vacancy' => null,
        'bonus' => null,
        'gross_salary' => null,
        'employee_assemp' => null,
        'employee_rrq' => null,
        'employee_rqap' => null,
        'employee_rpc' => null,
        'employee_impot_fed' => null,
        'employee_impot_prov' => null,
        'employee_taxable_benefits' => null,
        'voluntary_retirement_savings_plan' => null,
        'registered_retirement_savings_plan' => null,
        'tax_free_saving_account' => null,
        'employer_assemp' => null,
        'employer_rrq' => null,
        'employer_rqap' => null,
        'employer_rpc' => null,
        'employer_fss' => null,
        'employer_csst' => null,
        'allowance_total' => null,
        'net_salary' => null,
        'payrolls' => 'iri-reference',
        'payroll' => 'iri-reference',
        'notes' => null,
        'owning_corporation' => 'iri-reference',
        'shortcode' => null,
        'deleted_at' => 'date-time',
        'id' => null,
        'slug' => null,
        'custom_properties' => null,
        'custom_data' => null,
        'created_at' => 'date-time',
        'updated_at' => 'date-time',
        'tags' => null,
        'disabled_at' => 'date-time',
        'entity_files' => null,
        'upload_filename' => null,
        'upload_subfolder' => null,
        'upload_file' => null,
        'upload_file_link' => null,
        'payroll_employees' => null,
        'payroll_listing' => null,
        'allowances' => null,
        'timesheets' => null,
        'timesheets_listing' => null,
        'bonis' => null,
        'to_string' => null,
        'total_employee_das_amount' => null,
        'total_employer_das_amount' => null,
        'total_provincial' => null,
        'total_federal' => null,
        'employe_saving_taxable_reduction' => null,
        'custom_properties_listing' => null,
        'api_shortname' => null,
        'table_name' => null,
        'full_entity_string' => null,
        'anonymous_token' => null,
        'token_string' => null,
        'entity_metatada_endpoint' => null,
        'files_listing' => null,
        'modification_history_listing' => null,
        'notes_listing' => null,
        'ownerships_listing' => null,
        'approvals_listing' => null,
        'f_qcn' => null,
        'unique_id' => null,
        'api_custom_data' => null,
        'timestamp' => 'date-time',
        'deleted' => null,
        'taggable_type' => null,
        'taggable_id' => null,
        'tagging_listing' => null,
        'enabled' => null,
        'enabled_virtual' => null,
        'disabled' => null,
        'upload_subfolder' => null,
        'upload_file' => null,
        'upload_file_link' => null,
        'entity_storage_folder' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'created_date' => false,
        'date_start' => false,
        'date_end' => false,
        'employee' => true,
        'nb_hours' => false,
        'holiday_nb_hours' => false,
        'nb_employee' => false,
        'employee_hour_salary' => false,
        'vacancy_paid' => false,
        'vacancy_amount' => false,
        'employee_vacancy' => false,
        'bonus' => false,
        'gross_salary' => false,
        'employee_assemp' => false,
        'employee_rrq' => false,
        'employee_rqap' => false,
        'employee_rpc' => false,
        'employee_impot_fed' => false,
        'employee_impot_prov' => false,
        'employee_taxable_benefits' => false,
        'voluntary_retirement_savings_plan' => false,
        'registered_retirement_savings_plan' => false,
        'tax_free_saving_account' => false,
        'employer_assemp' => false,
        'employer_rrq' => false,
        'employer_rqap' => false,
        'employer_rpc' => false,
        'employer_fss' => false,
        'employer_csst' => false,
        'allowance_total' => false,
        'net_salary' => false,
        'payrolls' => false,
        'payroll' => true,
        'notes' => true,
        'owning_corporation' => false,
        'shortcode' => false,
        'deleted_at' => true,
        'id' => false,
        'slug' => false,
        'custom_properties' => true,
        'custom_data' => true,
        'created_at' => false,
        'updated_at' => false,
        'tags' => false,
        'disabled_at' => true,
        'entity_files' => false,
        'upload_filename' => false,
        'upload_subfolder' => false,
        'upload_file' => false,
        'upload_file_link' => false,
        'payroll_employees' => false,
        'payroll_listing' => false,
        'allowances' => false,
        'timesheets' => false,
        'timesheets_listing' => false,
        'bonis' => false,
        'to_string' => false,
        'total_employee_das_amount' => false,
        'total_employer_das_amount' => false,
        'total_provincial' => false,
        'total_federal' => false,
        'employe_saving_taxable_reduction' => false,
        'custom_properties_listing' => false,
        'api_shortname' => false,
        'table_name' => false,
        'full_entity_string' => false,
        'anonymous_token' => false,
        'token_string' => false,
        'entity_metatada_endpoint' => false,
        'files_listing' => false,
        'modification_history_listing' => false,
        'notes_listing' => false,
        'ownerships_listing' => false,
        'approvals_listing' => false,
        'f_qcn' => false,
        'unique_id' => false,
        'api_custom_data' => true,
        'timestamp' => false,
        'deleted' => false,
        'taggable_type' => true,
        'taggable_id' => false,
        'tagging_listing' => false,
        'enabled' => false,
        'enabled_virtual' => false,
        'disabled' => false,
        'upload_subfolder' => false,
        'upload_file' => false,
        'upload_file_link' => false,
        'entity_storage_folder' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'created_date' => 'createdDate',
        'date_start' => 'dateStart',
        'date_end' => 'dateEnd',
        'employee' => 'employee',
        'nb_hours' => 'nbHours',
        'holiday_nb_hours' => 'holidayNbHours',
        'nb_employee' => 'nbEmployee',
        'employee_hour_salary' => 'employeeHourSalary',
        'vacancy_paid' => 'vacancyPaid',
        'vacancy_amount' => 'vacancyAmount',
        'employee_vacancy' => 'employeeVacancy',
        'bonus' => 'bonus',
        'gross_salary' => 'grossSalary',
        'employee_assemp' => 'employeeAssemp',
        'employee_rrq' => 'employeeRrq',
        'employee_rqap' => 'employeeRqap',
        'employee_rpc' => 'employeeRpc',
        'employee_impot_fed' => 'employeeImpotFed',
        'employee_impot_prov' => 'employeeImpotProv',
        'employee_taxable_benefits' => 'employeeTaxableBenefits',
        'voluntary_retirement_savings_plan' => 'voluntaryRetirementSavingsPlan',
        'registered_retirement_savings_plan' => 'registeredRetirementSavingsPlan',
        'tax_free_saving_account' => 'taxFreeSavingAccount',
        'employer_assemp' => 'employerAssemp',
        'employer_rrq' => 'employerRrq',
        'employer_rqap' => 'employerRqap',
        'employer_rpc' => 'employerRpc',
        'employer_fss' => 'employerFss',
        'employer_csst' => 'employerCsst',
        'allowance_total' => 'allowanceTotal',
        'net_salary' => 'netSalary',
        'payrolls' => 'payrolls',
        'payroll' => 'payroll',
        'notes' => 'notes',
        'owning_corporation' => 'owningCorporation',
        'shortcode' => 'shortcode',
        'deleted_at' => 'deletedAt',
        'id' => 'id',
        'slug' => 'slug',
        'custom_properties' => 'customProperties',
        'custom_data' => 'customData',
        'created_at' => 'createdAt',
        'updated_at' => 'updatedAt',
        'tags' => 'tags',
        'disabled_at' => 'disabledAt',
        'entity_files' => 'entityFiles',
        'upload_filename' => 'upload_filename',
        'upload_subfolder' => 'upload_subfolder',
        'upload_file' => 'upload_file',
        'upload_file_link' => 'upload_file_link',
        'payroll_employees' => 'payrollEmployees',
        'payroll_listing' => 'payrollListing',
        'allowances' => 'allowances',
        'timesheets' => 'timesheets',
        'timesheets_listing' => 'timesheetsListing',
        'bonis' => 'bonis',
        'to_string' => 'toString',
        'total_employee_das_amount' => 'totalEmployeeDasAmount',
        'total_employer_das_amount' => 'totalEmployerDasAmount',
        'total_provincial' => 'totalProvincial',
        'total_federal' => 'totalFederal',
        'employe_saving_taxable_reduction' => 'employeSavingTaxableReduction',
        'custom_properties_listing' => 'customPropertiesListing',
        'api_shortname' => 'apiShortname',
        'table_name' => 'tableName',
        'full_entity_string' => 'fullEntityString',
        'anonymous_token' => 'anonymousToken',
        'token_string' => 'tokenString',
        'entity_metatada_endpoint' => 'entityMetatadaEndpoint',
        'files_listing' => 'filesListing',
        'modification_history_listing' => 'modificationHistoryListing',
        'notes_listing' => 'notesListing',
        'ownerships_listing' => 'ownershipsListing',
        'approvals_listing' => 'approvalsListing',
        'f_qcn' => 'fQCN',
        'unique_id' => 'uniqueId',
        'api_custom_data' => 'apiCustomData',
        'timestamp' => 'timestamp',
        'deleted' => 'deleted',
        'taggable_type' => 'taggableType',
        'taggable_id' => 'taggableId',
        'tagging_listing' => 'taggingListing',
        'enabled' => 'enabled',
        'enabled_virtual' => 'enabledVirtual',
        'disabled' => 'disabled',
        'upload_subfolder' => 'upload_Subfolder',
        'upload_file' => 'upload_File',
        'upload_file_link' => 'upload_File_Link',
        'entity_storage_folder' => 'entityStorageFolder'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'created_date' => 'setCreatedDate',
        'date_start' => 'setDateStart',
        'date_end' => 'setDateEnd',
        'employee' => 'setEmployee',
        'nb_hours' => 'setNbHours',
        'holiday_nb_hours' => 'setHolidayNbHours',
        'nb_employee' => 'setNbEmployee',
        'employee_hour_salary' => 'setEmployeeHourSalary',
        'vacancy_paid' => 'setVacancyPaid',
        'vacancy_amount' => 'setVacancyAmount',
        'employee_vacancy' => 'setEmployeeVacancy',
        'bonus' => 'setBonus',
        'gross_salary' => 'setGrossSalary',
        'employee_assemp' => 'setEmployeeAssemp',
        'employee_rrq' => 'setEmployeeRrq',
        'employee_rqap' => 'setEmployeeRqap',
        'employee_rpc' => 'setEmployeeRpc',
        'employee_impot_fed' => 'setEmployeeImpotFed',
        'employee_impot_prov' => 'setEmployeeImpotProv',
        'employee_taxable_benefits' => 'setEmployeeTaxableBenefits',
        'voluntary_retirement_savings_plan' => 'setVoluntaryRetirementSavingsPlan',
        'registered_retirement_savings_plan' => 'setRegisteredRetirementSavingsPlan',
        'tax_free_saving_account' => 'setTaxFreeSavingAccount',
        'employer_assemp' => 'setEmployerAssemp',
        'employer_rrq' => 'setEmployerRrq',
        'employer_rqap' => 'setEmployerRqap',
        'employer_rpc' => 'setEmployerRpc',
        'employer_fss' => 'setEmployerFss',
        'employer_csst' => 'setEmployerCsst',
        'allowance_total' => 'setAllowanceTotal',
        'net_salary' => 'setNetSalary',
        'payrolls' => 'setPayrolls',
        'payroll' => 'setPayroll',
        'notes' => 'setNotes',
        'owning_corporation' => 'setOwningCorporation',
        'shortcode' => 'setShortcode',
        'deleted_at' => 'setDeletedAt',
        'id' => 'setId',
        'slug' => 'setSlug',
        'custom_properties' => 'setCustomProperties',
        'custom_data' => 'setCustomData',
        'created_at' => 'setCreatedAt',
        'updated_at' => 'setUpdatedAt',
        'tags' => 'setTags',
        'disabled_at' => 'setDisabledAt',
        'entity_files' => 'setEntityFiles',
        'upload_filename' => 'setUploadFilename',
        'upload_subfolder' => 'setUploadSubfolder',
        'upload_file' => 'setUploadFile',
        'upload_file_link' => 'setUploadFileLink',
        'payroll_employees' => 'setPayrollEmployees',
        'payroll_listing' => 'setPayrollListing',
        'allowances' => 'setAllowances',
        'timesheets' => 'setTimesheets',
        'timesheets_listing' => 'setTimesheetsListing',
        'bonis' => 'setBonis',
        'to_string' => 'setToString',
        'total_employee_das_amount' => 'setTotalEmployeeDasAmount',
        'total_employer_das_amount' => 'setTotalEmployerDasAmount',
        'total_provincial' => 'setTotalProvincial',
        'total_federal' => 'setTotalFederal',
        'employe_saving_taxable_reduction' => 'setEmployeSavingTaxableReduction',
        'custom_properties_listing' => 'setCustomPropertiesListing',
        'api_shortname' => 'setApiShortname',
        'table_name' => 'setTableName',
        'full_entity_string' => 'setFullEntityString',
        'anonymous_token' => 'setAnonymousToken',
        'token_string' => 'setTokenString',
        'entity_metatada_endpoint' => 'setEntityMetatadaEndpoint',
        'files_listing' => 'setFilesListing',
        'modification_history_listing' => 'setModificationHistoryListing',
        'notes_listing' => 'setNotesListing',
        'ownerships_listing' => 'setOwnershipsListing',
        'approvals_listing' => 'setApprovalsListing',
        'f_qcn' => 'setFQcn',
        'unique_id' => 'setUniqueId',
        'api_custom_data' => 'setApiCustomData',
        'timestamp' => 'setTimestamp',
        'deleted' => 'setDeleted',
        'taggable_type' => 'setTaggableType',
        'taggable_id' => 'setTaggableId',
        'tagging_listing' => 'setTaggingListing',
        'enabled' => 'setEnabled',
        'enabled_virtual' => 'setEnabledVirtual',
        'disabled' => 'setDisabled',
        'upload_subfolder' => 'setUploadSubfolder',
        'upload_file' => 'setUploadFile',
        'upload_file_link' => 'setUploadFileLink',
        'entity_storage_folder' => 'setEntityStorageFolder'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'created_date' => 'getCreatedDate',
        'date_start' => 'getDateStart',
        'date_end' => 'getDateEnd',
        'employee' => 'getEmployee',
        'nb_hours' => 'getNbHours',
        'holiday_nb_hours' => 'getHolidayNbHours',
        'nb_employee' => 'getNbEmployee',
        'employee_hour_salary' => 'getEmployeeHourSalary',
        'vacancy_paid' => 'getVacancyPaid',
        'vacancy_amount' => 'getVacancyAmount',
        'employee_vacancy' => 'getEmployeeVacancy',
        'bonus' => 'getBonus',
        'gross_salary' => 'getGrossSalary',
        'employee_assemp' => 'getEmployeeAssemp',
        'employee_rrq' => 'getEmployeeRrq',
        'employee_rqap' => 'getEmployeeRqap',
        'employee_rpc' => 'getEmployeeRpc',
        'employee_impot_fed' => 'getEmployeeImpotFed',
        'employee_impot_prov' => 'getEmployeeImpotProv',
        'employee_taxable_benefits' => 'getEmployeeTaxableBenefits',
        'voluntary_retirement_savings_plan' => 'getVoluntaryRetirementSavingsPlan',
        'registered_retirement_savings_plan' => 'getRegisteredRetirementSavingsPlan',
        'tax_free_saving_account' => 'getTaxFreeSavingAccount',
        'employer_assemp' => 'getEmployerAssemp',
        'employer_rrq' => 'getEmployerRrq',
        'employer_rqap' => 'getEmployerRqap',
        'employer_rpc' => 'getEmployerRpc',
        'employer_fss' => 'getEmployerFss',
        'employer_csst' => 'getEmployerCsst',
        'allowance_total' => 'getAllowanceTotal',
        'net_salary' => 'getNetSalary',
        'payrolls' => 'getPayrolls',
        'payroll' => 'getPayroll',
        'notes' => 'getNotes',
        'owning_corporation' => 'getOwningCorporation',
        'shortcode' => 'getShortcode',
        'deleted_at' => 'getDeletedAt',
        'id' => 'getId',
        'slug' => 'getSlug',
        'custom_properties' => 'getCustomProperties',
        'custom_data' => 'getCustomData',
        'created_at' => 'getCreatedAt',
        'updated_at' => 'getUpdatedAt',
        'tags' => 'getTags',
        'disabled_at' => 'getDisabledAt',
        'entity_files' => 'getEntityFiles',
        'upload_filename' => 'getUploadFilename',
        'upload_subfolder' => 'getUploadSubfolder',
        'upload_file' => 'getUploadFile',
        'upload_file_link' => 'getUploadFileLink',
        'payroll_employees' => 'getPayrollEmployees',
        'payroll_listing' => 'getPayrollListing',
        'allowances' => 'getAllowances',
        'timesheets' => 'getTimesheets',
        'timesheets_listing' => 'getTimesheetsListing',
        'bonis' => 'getBonis',
        'to_string' => 'getToString',
        'total_employee_das_amount' => 'getTotalEmployeeDasAmount',
        'total_employer_das_amount' => 'getTotalEmployerDasAmount',
        'total_provincial' => 'getTotalProvincial',
        'total_federal' => 'getTotalFederal',
        'employe_saving_taxable_reduction' => 'getEmployeSavingTaxableReduction',
        'custom_properties_listing' => 'getCustomPropertiesListing',
        'api_shortname' => 'getApiShortname',
        'table_name' => 'getTableName',
        'full_entity_string' => 'getFullEntityString',
        'anonymous_token' => 'getAnonymousToken',
        'token_string' => 'getTokenString',
        'entity_metatada_endpoint' => 'getEntityMetatadaEndpoint',
        'files_listing' => 'getFilesListing',
        'modification_history_listing' => 'getModificationHistoryListing',
        'notes_listing' => 'getNotesListing',
        'ownerships_listing' => 'getOwnershipsListing',
        'approvals_listing' => 'getApprovalsListing',
        'f_qcn' => 'getFQcn',
        'unique_id' => 'getUniqueId',
        'api_custom_data' => 'getApiCustomData',
        'timestamp' => 'getTimestamp',
        'deleted' => 'getDeleted',
        'taggable_type' => 'getTaggableType',
        'taggable_id' => 'getTaggableId',
        'tagging_listing' => 'getTaggingListing',
        'enabled' => 'getEnabled',
        'enabled_virtual' => 'getEnabledVirtual',
        'disabled' => 'getDisabled',
        'upload_subfolder' => 'getUploadSubfolder',
        'upload_file' => 'getUploadFile',
        'upload_file_link' => 'getUploadFileLink',
        'entity_storage_folder' => 'getEntityStorageFolder'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('created_date', $data ?? [], null);
        $this->setIfExists('date_start', $data ?? [], null);
        $this->setIfExists('date_end', $data ?? [], null);
        $this->setIfExists('employee', $data ?? [], null);
        $this->setIfExists('nb_hours', $data ?? [], null);
        $this->setIfExists('holiday_nb_hours', $data ?? [], null);
        $this->setIfExists('nb_employee', $data ?? [], null);
        $this->setIfExists('employee_hour_salary', $data ?? [], null);
        $this->setIfExists('vacancy_paid', $data ?? [], null);
        $this->setIfExists('vacancy_amount', $data ?? [], null);
        $this->setIfExists('employee_vacancy', $data ?? [], null);
        $this->setIfExists('bonus', $data ?? [], null);
        $this->setIfExists('gross_salary', $data ?? [], null);
        $this->setIfExists('employee_assemp', $data ?? [], null);
        $this->setIfExists('employee_rrq', $data ?? [], null);
        $this->setIfExists('employee_rqap', $data ?? [], null);
        $this->setIfExists('employee_rpc', $data ?? [], null);
        $this->setIfExists('employee_impot_fed', $data ?? [], null);
        $this->setIfExists('employee_impot_prov', $data ?? [], null);
        $this->setIfExists('employee_taxable_benefits', $data ?? [], null);
        $this->setIfExists('voluntary_retirement_savings_plan', $data ?? [], null);
        $this->setIfExists('registered_retirement_savings_plan', $data ?? [], null);
        $this->setIfExists('tax_free_saving_account', $data ?? [], null);
        $this->setIfExists('employer_assemp', $data ?? [], null);
        $this->setIfExists('employer_rrq', $data ?? [], null);
        $this->setIfExists('employer_rqap', $data ?? [], null);
        $this->setIfExists('employer_rpc', $data ?? [], null);
        $this->setIfExists('employer_fss', $data ?? [], null);
        $this->setIfExists('employer_csst', $data ?? [], null);
        $this->setIfExists('allowance_total', $data ?? [], null);
        $this->setIfExists('net_salary', $data ?? [], null);
        $this->setIfExists('payrolls', $data ?? [], null);
        $this->setIfExists('payroll', $data ?? [], null);
        $this->setIfExists('notes', $data ?? [], null);
        $this->setIfExists('owning_corporation', $data ?? [], null);
        $this->setIfExists('shortcode', $data ?? [], 'RAS');
        $this->setIfExists('deleted_at', $data ?? [], null);
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('slug', $data ?? [], null);
        $this->setIfExists('custom_properties', $data ?? [], null);
        $this->setIfExists('custom_data', $data ?? [], null);
        $this->setIfExists('created_at', $data ?? [], null);
        $this->setIfExists('updated_at', $data ?? [], null);
        $this->setIfExists('tags', $data ?? [], null);
        $this->setIfExists('disabled_at', $data ?? [], null);
        $this->setIfExists('entity_files', $data ?? [], null);
        $this->setIfExists('upload_filename', $data ?? [], null);
        $this->setIfExists('upload_subfolder', $data ?? [], null);
        $this->setIfExists('upload_file', $data ?? [], null);
        $this->setIfExists('upload_file_link', $data ?? [], null);
        $this->setIfExists('payroll_employees', $data ?? [], null);
        $this->setIfExists('payroll_listing', $data ?? [], null);
        $this->setIfExists('allowances', $data ?? [], null);
        $this->setIfExists('timesheets', $data ?? [], null);
        $this->setIfExists('timesheets_listing', $data ?? [], null);
        $this->setIfExists('bonis', $data ?? [], null);
        $this->setIfExists('to_string', $data ?? [], null);
        $this->setIfExists('total_employee_das_amount', $data ?? [], null);
        $this->setIfExists('total_employer_das_amount', $data ?? [], null);
        $this->setIfExists('total_provincial', $data ?? [], null);
        $this->setIfExists('total_federal', $data ?? [], null);
        $this->setIfExists('employe_saving_taxable_reduction', $data ?? [], null);
        $this->setIfExists('custom_properties_listing', $data ?? [], null);
        $this->setIfExists('api_shortname', $data ?? [], null);
        $this->setIfExists('table_name', $data ?? [], null);
        $this->setIfExists('full_entity_string', $data ?? [], null);
        $this->setIfExists('anonymous_token', $data ?? [], null);
        $this->setIfExists('token_string', $data ?? [], null);
        $this->setIfExists('entity_metatada_endpoint', $data ?? [], null);
        $this->setIfExists('files_listing', $data ?? [], null);
        $this->setIfExists('modification_history_listing', $data ?? [], null);
        $this->setIfExists('notes_listing', $data ?? [], null);
        $this->setIfExists('ownerships_listing', $data ?? [], null);
        $this->setIfExists('approvals_listing', $data ?? [], null);
        $this->setIfExists('f_qcn', $data ?? [], null);
        $this->setIfExists('unique_id', $data ?? [], null);
        $this->setIfExists('api_custom_data', $data ?? [], null);
        $this->setIfExists('timestamp', $data ?? [], null);
        $this->setIfExists('deleted', $data ?? [], null);
        $this->setIfExists('taggable_type', $data ?? [], null);
        $this->setIfExists('taggable_id', $data ?? [], null);
        $this->setIfExists('tagging_listing', $data ?? [], null);
        $this->setIfExists('enabled', $data ?? [], null);
        $this->setIfExists('enabled_virtual', $data ?? [], null);
        $this->setIfExists('disabled', $data ?? [], null);
        $this->setIfExists('upload_subfolder', $data ?? [], null);
        $this->setIfExists('upload_file', $data ?? [], null);
        $this->setIfExists('upload_file_link', $data ?? [], null);
        $this->setIfExists('entity_storage_folder', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['date_start'] === null) {
            $invalidProperties[] = "'date_start' can't be null";
        }
        if ($this->container['date_end'] === null) {
            $invalidProperties[] = "'date_end' can't be null";
        }
        if ($this->container['nb_hours'] === null) {
            $invalidProperties[] = "'nb_hours' can't be null";
        }
        if ($this->container['holiday_nb_hours'] === null) {
            $invalidProperties[] = "'holiday_nb_hours' can't be null";
        }
        if ($this->container['nb_employee'] === null) {
            $invalidProperties[] = "'nb_employee' can't be null";
        }
        if ($this->container['employee_hour_salary'] === null) {
            $invalidProperties[] = "'employee_hour_salary' can't be null";
        }
        if ($this->container['vacancy_paid'] === null) {
            $invalidProperties[] = "'vacancy_paid' can't be null";
        }
        if ($this->container['vacancy_amount'] === null) {
            $invalidProperties[] = "'vacancy_amount' can't be null";
        }
        if ($this->container['employee_vacancy'] === null) {
            $invalidProperties[] = "'employee_vacancy' can't be null";
        }
        if ($this->container['bonus'] === null) {
            $invalidProperties[] = "'bonus' can't be null";
        }
        if ($this->container['gross_salary'] === null) {
            $invalidProperties[] = "'gross_salary' can't be null";
        }
        if ($this->container['employee_assemp'] === null) {
            $invalidProperties[] = "'employee_assemp' can't be null";
        }
        if ($this->container['employee_rrq'] === null) {
            $invalidProperties[] = "'employee_rrq' can't be null";
        }
        if ($this->container['employee_rqap'] === null) {
            $invalidProperties[] = "'employee_rqap' can't be null";
        }
        if ($this->container['employee_rpc'] === null) {
            $invalidProperties[] = "'employee_rpc' can't be null";
        }
        if ($this->container['employee_impot_fed'] === null) {
            $invalidProperties[] = "'employee_impot_fed' can't be null";
        }
        if ($this->container['employee_impot_prov'] === null) {
            $invalidProperties[] = "'employee_impot_prov' can't be null";
        }
        if ($this->container['employee_taxable_benefits'] === null) {
            $invalidProperties[] = "'employee_taxable_benefits' can't be null";
        }
        if ($this->container['voluntary_retirement_savings_plan'] === null) {
            $invalidProperties[] = "'voluntary_retirement_savings_plan' can't be null";
        }
        if ($this->container['registered_retirement_savings_plan'] === null) {
            $invalidProperties[] = "'registered_retirement_savings_plan' can't be null";
        }
        if ($this->container['tax_free_saving_account'] === null) {
            $invalidProperties[] = "'tax_free_saving_account' can't be null";
        }
        if ($this->container['employer_assemp'] === null) {
            $invalidProperties[] = "'employer_assemp' can't be null";
        }
        if ($this->container['employer_rrq'] === null) {
            $invalidProperties[] = "'employer_rrq' can't be null";
        }
        if ($this->container['employer_rqap'] === null) {
            $invalidProperties[] = "'employer_rqap' can't be null";
        }
        if ($this->container['employer_rpc'] === null) {
            $invalidProperties[] = "'employer_rpc' can't be null";
        }
        if ($this->container['employer_fss'] === null) {
            $invalidProperties[] = "'employer_fss' can't be null";
        }
        if ($this->container['employer_csst'] === null) {
            $invalidProperties[] = "'employer_csst' can't be null";
        }
        if ($this->container['allowance_total'] === null) {
            $invalidProperties[] = "'allowance_total' can't be null";
        }
        if ($this->container['net_salary'] === null) {
            $invalidProperties[] = "'net_salary' can't be null";
        }
        if ($this->container['slug'] === null) {
            $invalidProperties[] = "'slug' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets created_date
     *
     * @return \DateTime|null
     */
    public function getCreatedDate()
    {
        return $this->container['created_date'];
    }

    /**
     * Sets created_date
     *
     * @param \DateTime|null $created_date created_date
     *
     * @return self
     */
    public function setCreatedDate($created_date)
    {
        if (is_null($created_date)) {
            throw new \InvalidArgumentException('non-nullable created_date cannot be null');
        }
        $this->container['created_date'] = $created_date;

        return $this;
    }

    /**
     * Gets date_start
     *
     * @return \DateTime
     */
    public function getDateStart()
    {
        return $this->container['date_start'];
    }

    /**
     * Sets date_start
     *
     * @param \DateTime $date_start date_start
     *
     * @return self
     */
    public function setDateStart($date_start)
    {
        if (is_null($date_start)) {
            throw new \InvalidArgumentException('non-nullable date_start cannot be null');
        }
        $this->container['date_start'] = $date_start;

        return $this;
    }

    /**
     * Gets date_end
     *
     * @return \DateTime
     */
    public function getDateEnd()
    {
        return $this->container['date_end'];
    }

    /**
     * Sets date_end
     *
     * @param \DateTime $date_end date_end
     *
     * @return self
     */
    public function setDateEnd($date_end)
    {
        if (is_null($date_end)) {
            throw new \InvalidArgumentException('non-nullable date_end cannot be null');
        }
        $this->container['date_end'] = $date_end;

        return $this;
    }

    /**
     * Gets employee
     *
     * @return string|null
     */
    public function getEmployee()
    {
        return $this->container['employee'];
    }

    /**
     * Sets employee
     *
     * @param string|null $employee Get employesId.
     *
     * @return self
     */
    public function setEmployee($employee)
    {
        if (is_null($employee)) {
            array_push($this->openAPINullablesSetToNull, 'employee');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('employee', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['employee'] = $employee;

        return $this;
    }

    /**
     * Gets nb_hours
     *
     * @return string
     */
    public function getNbHours()
    {
        return $this->container['nb_hours'];
    }

    /**
     * Sets nb_hours
     *
     * @param string $nb_hours nb_hours
     *
     * @return self
     */
    public function setNbHours($nb_hours)
    {
        if (is_null($nb_hours)) {
            throw new \InvalidArgumentException('non-nullable nb_hours cannot be null');
        }
        $this->container['nb_hours'] = $nb_hours;

        return $this;
    }

    /**
     * Gets holiday_nb_hours
     *
     * @return string
     */
    public function getHolidayNbHours()
    {
        return $this->container['holiday_nb_hours'];
    }

    /**
     * Sets holiday_nb_hours
     *
     * @param string $holiday_nb_hours holiday_nb_hours
     *
     * @return self
     */
    public function setHolidayNbHours($holiday_nb_hours)
    {
        if (is_null($holiday_nb_hours)) {
            throw new \InvalidArgumentException('non-nullable holiday_nb_hours cannot be null');
        }
        $this->container['holiday_nb_hours'] = $holiday_nb_hours;

        return $this;
    }

    /**
     * Gets nb_employee
     *
     * @return int
     */
    public function getNbEmployee()
    {
        return $this->container['nb_employee'];
    }

    /**
     * Sets nb_employee
     *
     * @param int $nb_employee nb_employee
     *
     * @return self
     */
    public function setNbEmployee($nb_employee)
    {
        if (is_null($nb_employee)) {
            throw new \InvalidArgumentException('non-nullable nb_employee cannot be null');
        }
        $this->container['nb_employee'] = $nb_employee;

        return $this;
    }

    /**
     * Gets employee_hour_salary
     *
     * @return string
     */
    public function getEmployeeHourSalary()
    {
        return $this->container['employee_hour_salary'];
    }

    /**
     * Sets employee_hour_salary
     *
     * @param string $employee_hour_salary employee_hour_salary
     *
     * @return self
     */
    public function setEmployeeHourSalary($employee_hour_salary)
    {
        if (is_null($employee_hour_salary)) {
            throw new \InvalidArgumentException('non-nullable employee_hour_salary cannot be null');
        }
        $this->container['employee_hour_salary'] = $employee_hour_salary;

        return $this;
    }

    /**
     * Gets vacancy_paid
     *
     * @return string
     */
    public function getVacancyPaid()
    {
        return $this->container['vacancy_paid'];
    }

    /**
     * Sets vacancy_paid
     *
     * @param string $vacancy_paid vacancy_paid
     *
     * @return self
     */
    public function setVacancyPaid($vacancy_paid)
    {
        if (is_null($vacancy_paid)) {
            throw new \InvalidArgumentException('non-nullable vacancy_paid cannot be null');
        }
        $this->container['vacancy_paid'] = $vacancy_paid;

        return $this;
    }

    /**
     * Gets vacancy_amount
     *
     * @return string
     */
    public function getVacancyAmount()
    {
        return $this->container['vacancy_amount'];
    }

    /**
     * Sets vacancy_amount
     *
     * @param string $vacancy_amount vacancy_amount
     *
     * @return self
     */
    public function setVacancyAmount($vacancy_amount)
    {
        if (is_null($vacancy_amount)) {
            throw new \InvalidArgumentException('non-nullable vacancy_amount cannot be null');
        }
        $this->container['vacancy_amount'] = $vacancy_amount;

        return $this;
    }

    /**
     * Gets employee_vacancy
     *
     * @return string
     */
    public function getEmployeeVacancy()
    {
        return $this->container['employee_vacancy'];
    }

    /**
     * Sets employee_vacancy
     *
     * @param string $employee_vacancy employee_vacancy
     *
     * @return self
     */
    public function setEmployeeVacancy($employee_vacancy)
    {
        if (is_null($employee_vacancy)) {
            throw new \InvalidArgumentException('non-nullable employee_vacancy cannot be null');
        }
        $this->container['employee_vacancy'] = $employee_vacancy;

        return $this;
    }

    /**
     * Gets bonus
     *
     * @return string
     */
    public function getBonus()
    {
        return $this->container['bonus'];
    }

    /**
     * Sets bonus
     *
     * @param string $bonus bonus
     *
     * @return self
     */
    public function setBonus($bonus)
    {
        if (is_null($bonus)) {
            throw new \InvalidArgumentException('non-nullable bonus cannot be null');
        }
        $this->container['bonus'] = $bonus;

        return $this;
    }

    /**
     * Gets gross_salary
     *
     * @return string
     */
    public function getGrossSalary()
    {
        return $this->container['gross_salary'];
    }

    /**
     * Sets gross_salary
     *
     * @param string $gross_salary gross_salary
     *
     * @return self
     */
    public function setGrossSalary($gross_salary)
    {
        if (is_null($gross_salary)) {
            throw new \InvalidArgumentException('non-nullable gross_salary cannot be null');
        }
        $this->container['gross_salary'] = $gross_salary;

        return $this;
    }

    /**
     * Gets employee_assemp
     *
     * @return string
     */
    public function getEmployeeAssemp()
    {
        return $this->container['employee_assemp'];
    }

    /**
     * Sets employee_assemp
     *
     * @param string $employee_assemp employee_assemp
     *
     * @return self
     */
    public function setEmployeeAssemp($employee_assemp)
    {
        if (is_null($employee_assemp)) {
            throw new \InvalidArgumentException('non-nullable employee_assemp cannot be null');
        }
        $this->container['employee_assemp'] = $employee_assemp;

        return $this;
    }

    /**
     * Gets employee_rrq
     *
     * @return string
     */
    public function getEmployeeRrq()
    {
        return $this->container['employee_rrq'];
    }

    /**
     * Sets employee_rrq
     *
     * @param string $employee_rrq employee_rrq
     *
     * @return self
     */
    public function setEmployeeRrq($employee_rrq)
    {
        if (is_null($employee_rrq)) {
            throw new \InvalidArgumentException('non-nullable employee_rrq cannot be null');
        }
        $this->container['employee_rrq'] = $employee_rrq;

        return $this;
    }

    /**
     * Gets employee_rqap
     *
     * @return string
     */
    public function getEmployeeRqap()
    {
        return $this->container['employee_rqap'];
    }

    /**
     * Sets employee_rqap
     *
     * @param string $employee_rqap employee_rqap
     *
     * @return self
     */
    public function setEmployeeRqap($employee_rqap)
    {
        if (is_null($employee_rqap)) {
            throw new \InvalidArgumentException('non-nullable employee_rqap cannot be null');
        }
        $this->container['employee_rqap'] = $employee_rqap;

        return $this;
    }

    /**
     * Gets employee_rpc
     *
     * @return string
     */
    public function getEmployeeRpc()
    {
        return $this->container['employee_rpc'];
    }

    /**
     * Sets employee_rpc
     *
     * @param string $employee_rpc employee_rpc
     *
     * @return self
     */
    public function setEmployeeRpc($employee_rpc)
    {
        if (is_null($employee_rpc)) {
            throw new \InvalidArgumentException('non-nullable employee_rpc cannot be null');
        }
        $this->container['employee_rpc'] = $employee_rpc;

        return $this;
    }

    /**
     * Gets employee_impot_fed
     *
     * @return string
     */
    public function getEmployeeImpotFed()
    {
        return $this->container['employee_impot_fed'];
    }

    /**
     * Sets employee_impot_fed
     *
     * @param string $employee_impot_fed employee_impot_fed
     *
     * @return self
     */
    public function setEmployeeImpotFed($employee_impot_fed)
    {
        if (is_null($employee_impot_fed)) {
            throw new \InvalidArgumentException('non-nullable employee_impot_fed cannot be null');
        }
        $this->container['employee_impot_fed'] = $employee_impot_fed;

        return $this;
    }

    /**
     * Gets employee_impot_prov
     *
     * @return string
     */
    public function getEmployeeImpotProv()
    {
        return $this->container['employee_impot_prov'];
    }

    /**
     * Sets employee_impot_prov
     *
     * @param string $employee_impot_prov employee_impot_prov
     *
     * @return self
     */
    public function setEmployeeImpotProv($employee_impot_prov)
    {
        if (is_null($employee_impot_prov)) {
            throw new \InvalidArgumentException('non-nullable employee_impot_prov cannot be null');
        }
        $this->container['employee_impot_prov'] = $employee_impot_prov;

        return $this;
    }

    /**
     * Gets employee_taxable_benefits
     *
     * @return string
     */
    public function getEmployeeTaxableBenefits()
    {
        return $this->container['employee_taxable_benefits'];
    }

    /**
     * Sets employee_taxable_benefits
     *
     * @param string $employee_taxable_benefits EmployeeTaxableBenefits will influence the TaxeFed & TaxeProv as an increase amount
     *
     * @return self
     */
    public function setEmployeeTaxableBenefits($employee_taxable_benefits)
    {
        if (is_null($employee_taxable_benefits)) {
            throw new \InvalidArgumentException('non-nullable employee_taxable_benefits cannot be null');
        }
        $this->container['employee_taxable_benefits'] = $employee_taxable_benefits;

        return $this;
    }

    /**
     * Gets voluntary_retirement_savings_plan
     *
     * @return string
     */
    public function getVoluntaryRetirementSavingsPlan()
    {
        return $this->container['voluntary_retirement_savings_plan'];
    }

    /**
     * Sets voluntary_retirement_savings_plan
     *
     * @param string $voluntary_retirement_savings_plan Also call RVER / VRSP EmployeeSavingTaxableReduction will influence the TaxeFed & TaxeProv as an decrease amount
     *
     * @return self
     */
    public function setVoluntaryRetirementSavingsPlan($voluntary_retirement_savings_plan)
    {
        if (is_null($voluntary_retirement_savings_plan)) {
            throw new \InvalidArgumentException('non-nullable voluntary_retirement_savings_plan cannot be null');
        }
        $this->container['voluntary_retirement_savings_plan'] = $voluntary_retirement_savings_plan;

        return $this;
    }

    /**
     * Gets registered_retirement_savings_plan
     *
     * @return string
     */
    public function getRegisteredRetirementSavingsPlan()
    {
        return $this->container['registered_retirement_savings_plan'];
    }

    /**
     * Sets registered_retirement_savings_plan
     *
     * @param string $registered_retirement_savings_plan Also call REER / RRSP EmployeeSavingTaxableReduction will influence the TaxeFed & TaxeProv as an decrease amount
     *
     * @return self
     */
    public function setRegisteredRetirementSavingsPlan($registered_retirement_savings_plan)
    {
        if (is_null($registered_retirement_savings_plan)) {
            throw new \InvalidArgumentException('non-nullable registered_retirement_savings_plan cannot be null');
        }
        $this->container['registered_retirement_savings_plan'] = $registered_retirement_savings_plan;

        return $this;
    }

    /**
     * Gets tax_free_saving_account
     *
     * @return string
     */
    public function getTaxFreeSavingAccount()
    {
        return $this->container['tax_free_saving_account'];
    }

    /**
     * Sets tax_free_saving_account
     *
     * @param string $tax_free_saving_account Also call CELI / TFSA EmployeeSavingTaxableReduction not influence the TaxeFed & TaxeProv so amount will not change
     *
     * @return self
     */
    public function setTaxFreeSavingAccount($tax_free_saving_account)
    {
        if (is_null($tax_free_saving_account)) {
            throw new \InvalidArgumentException('non-nullable tax_free_saving_account cannot be null');
        }
        $this->container['tax_free_saving_account'] = $tax_free_saving_account;

        return $this;
    }

    /**
     * Gets employer_assemp
     *
     * @return string
     */
    public function getEmployerAssemp()
    {
        return $this->container['employer_assemp'];
    }

    /**
     * Sets employer_assemp
     *
     * @param string $employer_assemp employer_assemp
     *
     * @return self
     */
    public function setEmployerAssemp($employer_assemp)
    {
        if (is_null($employer_assemp)) {
            throw new \InvalidArgumentException('non-nullable employer_assemp cannot be null');
        }
        $this->container['employer_assemp'] = $employer_assemp;

        return $this;
    }

    /**
     * Gets employer_rrq
     *
     * @return string
     */
    public function getEmployerRrq()
    {
        return $this->container['employer_rrq'];
    }

    /**
     * Sets employer_rrq
     *
     * @param string $employer_rrq employer_rrq
     *
     * @return self
     */
    public function setEmployerRrq($employer_rrq)
    {
        if (is_null($employer_rrq)) {
            throw new \InvalidArgumentException('non-nullable employer_rrq cannot be null');
        }
        $this->container['employer_rrq'] = $employer_rrq;

        return $this;
    }

    /**
     * Gets employer_rqap
     *
     * @return string
     */
    public function getEmployerRqap()
    {
        return $this->container['employer_rqap'];
    }

    /**
     * Sets employer_rqap
     *
     * @param string $employer_rqap employer_rqap
     *
     * @return self
     */
    public function setEmployerRqap($employer_rqap)
    {
        if (is_null($employer_rqap)) {
            throw new \InvalidArgumentException('non-nullable employer_rqap cannot be null');
        }
        $this->container['employer_rqap'] = $employer_rqap;

        return $this;
    }

    /**
     * Gets employer_rpc
     *
     * @return string
     */
    public function getEmployerRpc()
    {
        return $this->container['employer_rpc'];
    }

    /**
     * Sets employer_rpc
     *
     * @param string $employer_rpc employer_rpc
     *
     * @return self
     */
    public function setEmployerRpc($employer_rpc)
    {
        if (is_null($employer_rpc)) {
            throw new \InvalidArgumentException('non-nullable employer_rpc cannot be null');
        }
        $this->container['employer_rpc'] = $employer_rpc;

        return $this;
    }

    /**
     * Gets employer_fss
     *
     * @return string
     */
    public function getEmployerFss()
    {
        return $this->container['employer_fss'];
    }

    /**
     * Sets employer_fss
     *
     * @param string $employer_fss employer_fss
     *
     * @return self
     */
    public function setEmployerFss($employer_fss)
    {
        if (is_null($employer_fss)) {
            throw new \InvalidArgumentException('non-nullable employer_fss cannot be null');
        }
        $this->container['employer_fss'] = $employer_fss;

        return $this;
    }

    /**
     * Gets employer_csst
     *
     * @return string
     */
    public function getEmployerCsst()
    {
        return $this->container['employer_csst'];
    }

    /**
     * Sets employer_csst
     *
     * @param string $employer_csst employer_csst
     *
     * @return self
     */
    public function setEmployerCsst($employer_csst)
    {
        if (is_null($employer_csst)) {
            throw new \InvalidArgumentException('non-nullable employer_csst cannot be null');
        }
        $this->container['employer_csst'] = $employer_csst;

        return $this;
    }

    /**
     * Gets allowance_total
     *
     * @return string
     */
    public function getAllowanceTotal()
    {
        return $this->container['allowance_total'];
    }

    /**
     * Sets allowance_total
     *
     * @param string $allowance_total allowance_total
     *
     * @return self
     */
    public function setAllowanceTotal($allowance_total)
    {
        if (is_null($allowance_total)) {
            throw new \InvalidArgumentException('non-nullable allowance_total cannot be null');
        }
        $this->container['allowance_total'] = $allowance_total;

        return $this;
    }

    /**
     * Gets net_salary
     *
     * @return string
     */
    public function getNetSalary()
    {
        return $this->container['net_salary'];
    }

    /**
     * Sets net_salary
     *
     * @param string $net_salary net_salary
     *
     * @return self
     */
    public function setNetSalary($net_salary)
    {
        if (is_null($net_salary)) {
            throw new \InvalidArgumentException('non-nullable net_salary cannot be null');
        }
        $this->container['net_salary'] = $net_salary;

        return $this;
    }

    /**
     * Gets payrolls
     *
     * @return string[]|null
     */
    public function getPayrolls()
    {
        return $this->container['payrolls'];
    }

    /**
     * Sets payrolls
     *
     * @param string[]|null $payrolls payrolls
     *
     * @return self
     */
    public function setPayrolls($payrolls)
    {
        if (is_null($payrolls)) {
            throw new \InvalidArgumentException('non-nullable payrolls cannot be null');
        }
        $this->container['payrolls'] = $payrolls;

        return $this;
    }

    /**
     * Gets payroll
     *
     * @return string|null
     */
    public function getPayroll()
    {
        return $this->container['payroll'];
    }

    /**
     * Sets payroll
     *
     * @param string|null $payroll payroll
     *
     * @return self
     */
    public function setPayroll($payroll)
    {
        if (is_null($payroll)) {
            array_push($this->openAPINullablesSetToNull, 'payroll');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('payroll', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['payroll'] = $payroll;

        return $this;
    }

    /**
     * Gets notes
     *
     * @return string|null
     */
    public function getNotes()
    {
        return $this->container['notes'];
    }

    /**
     * Sets notes
     *
     * @param string|null $notes notes
     *
     * @return self
     */
    public function setNotes($notes)
    {
        if (is_null($notes)) {
            array_push($this->openAPINullablesSetToNull, 'notes');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('notes', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['notes'] = $notes;

        return $this;
    }

    /**
     * Gets owning_corporation
     *
     * @return string|null
     */
    public function getOwningCorporation()
    {
        return $this->container['owning_corporation'];
    }

    /**
     * Sets owning_corporation
     *
     * @param string|null $owning_corporation owning_corporation
     *
     * @return self
     */
    public function setOwningCorporation($owning_corporation)
    {
        if (is_null($owning_corporation)) {
            throw new \InvalidArgumentException('non-nullable owning_corporation cannot be null');
        }
        $this->container['owning_corporation'] = $owning_corporation;

        return $this;
    }

    /**
     * Gets shortcode
     *
     * @return string|null
     */
    public function getShortcode()
    {
        return $this->container['shortcode'];
    }

    /**
     * Sets shortcode
     *
     * @param string|null $shortcode shortcode
     *
     * @return self
     */
    public function setShortcode($shortcode)
    {
        if (is_null($shortcode)) {
            throw new \InvalidArgumentException('non-nullable shortcode cannot be null');
        }
        $this->container['shortcode'] = $shortcode;

        return $this;
    }

    /**
     * Gets deleted_at
     *
     * @return \DateTime|null
     */
    public function getDeletedAt()
    {
        return $this->container['deleted_at'];
    }

    /**
     * Sets deleted_at
     *
     * @param \DateTime|null $deleted_at deleted_at
     *
     * @return self
     */
    public function setDeletedAt($deleted_at)
    {
        if (is_null($deleted_at)) {
            array_push($this->openAPINullablesSetToNull, 'deleted_at');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('deleted_at', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['deleted_at'] = $deleted_at;

        return $this;
    }

    /**
     * Gets id
     *
     * @return int|null
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param int|null $id DB Identifier
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets slug
     *
     * @return string
     */
    public function getSlug()
    {
        return $this->container['slug'];
    }

    /**
     * Sets slug
     *
     * @param string $slug DB Identifier
     *
     * @return self
     */
    public function setSlug($slug)
    {
        if (is_null($slug)) {
            throw new \InvalidArgumentException('non-nullable slug cannot be null');
        }
        $this->container['slug'] = $slug;

        return $this;
    }

    /**
     * Gets custom_properties
     *
     * @return mixed|null
     */
    public function getCustomProperties()
    {
        return $this->container['custom_properties'];
    }

    /**
     * Sets custom_properties
     *
     * @param mixed|null $custom_properties custom_properties
     *
     * @return self
     */
    public function setCustomProperties($custom_properties)
    {
        if (is_null($custom_properties)) {
            array_push($this->openAPINullablesSetToNull, 'custom_properties');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('custom_properties', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['custom_properties'] = $custom_properties;

        return $this;
    }

    /**
     * Gets custom_data
     *
     * @return string[]|null
     */
    public function getCustomData()
    {
        return $this->container['custom_data'];
    }

    /**
     * Sets custom_data
     *
     * @param string[]|null $custom_data custom_data
     *
     * @return self
     */
    public function setCustomData($custom_data)
    {
        if (is_null($custom_data)) {
            array_push($this->openAPINullablesSetToNull, 'custom_data');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('custom_data', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['custom_data'] = $custom_data;

        return $this;
    }

    /**
     * Gets created_at
     *
     * @return \DateTime|null
     */
    public function getCreatedAt()
    {
        return $this->container['created_at'];
    }

    /**
     * Sets created_at
     *
     * @param \DateTime|null $created_at created_at
     *
     * @return self
     */
    public function setCreatedAt($created_at)
    {
        if (is_null($created_at)) {
            throw new \InvalidArgumentException('non-nullable created_at cannot be null');
        }
        $this->container['created_at'] = $created_at;

        return $this;
    }

    /**
     * Gets updated_at
     *
     * @return \DateTime|null
     */
    public function getUpdatedAt()
    {
        return $this->container['updated_at'];
    }

    /**
     * Sets updated_at
     *
     * @param \DateTime|null $updated_at updated_at
     *
     * @return self
     */
    public function setUpdatedAt($updated_at)
    {
        if (is_null($updated_at)) {
            throw new \InvalidArgumentException('non-nullable updated_at cannot be null');
        }
        $this->container['updated_at'] = $updated_at;

        return $this;
    }

    /**
     * Gets tags
     *
     * @return string[]|null
     */
    public function getTags()
    {
        return $this->container['tags'];
    }

    /**
     * Sets tags
     *
     * @param string[]|null $tags tags
     *
     * @return self
     */
    public function setTags($tags)
    {
        if (is_null($tags)) {
            throw new \InvalidArgumentException('non-nullable tags cannot be null');
        }
        $this->container['tags'] = $tags;

        return $this;
    }

    /**
     * Gets disabled_at
     *
     * @return \DateTime|null
     */
    public function getDisabledAt()
    {
        return $this->container['disabled_at'];
    }

    /**
     * Sets disabled_at
     *
     * @param \DateTime|null $disabled_at disabled_at
     *
     * @return self
     */
    public function setDisabledAt($disabled_at)
    {
        if (is_null($disabled_at)) {
            array_push($this->openAPINullablesSetToNull, 'disabled_at');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('disabled_at', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['disabled_at'] = $disabled_at;

        return $this;
    }

    /**
     * Gets entity_files
     *
     * @return \OpenAPI\Client\Model\Collection|null
     */
    public function getEntityFiles()
    {
        return $this->container['entity_files'];
    }

    /**
     * Sets entity_files
     *
     * @param \OpenAPI\Client\Model\Collection|null $entity_files entity_files
     *
     * @return self
     */
    public function setEntityFiles($entity_files)
    {
        if (is_null($entity_files)) {
            throw new \InvalidArgumentException('non-nullable entity_files cannot be null');
        }
        $this->container['entity_files'] = $entity_files;

        return $this;
    }

    /**
     * Gets upload_filename
     *
     * @return string|null
     */
    public function getUploadFilename()
    {
        return $this->container['upload_filename'];
    }

    /**
     * Sets upload_filename
     *
     * @param string|null $upload_filename upload_filename
     *
     * @return self
     */
    public function setUploadFilename($upload_filename)
    {
        if (is_null($upload_filename)) {
            throw new \InvalidArgumentException('non-nullable upload_filename cannot be null');
        }
        $this->container['upload_filename'] = $upload_filename;

        return $this;
    }

    /**
     * Gets upload_subfolder
     *
     * @return string|null
     */
    public function getUploadSubfolder()
    {
        return $this->container['upload_subfolder'];
    }

    /**
     * Sets upload_subfolder
     *
     * @param string|null $upload_subfolder upload_subfolder
     *
     * @return self
     */
    public function setUploadSubfolder($upload_subfolder)
    {
        if (is_null($upload_subfolder)) {
            throw new \InvalidArgumentException('non-nullable upload_subfolder cannot be null');
        }
        $this->container['upload_subfolder'] = $upload_subfolder;

        return $this;
    }

    /**
     * Gets upload_file
     *
     * @return string|null
     */
    public function getUploadFile()
    {
        return $this->container['upload_file'];
    }

    /**
     * Sets upload_file
     *
     * @param string|null $upload_file upload_file
     *
     * @return self
     */
    public function setUploadFile($upload_file)
    {
        if (is_null($upload_file)) {
            throw new \InvalidArgumentException('non-nullable upload_file cannot be null');
        }
        $this->container['upload_file'] = $upload_file;

        return $this;
    }

    /**
     * Gets upload_file_link
     *
     * @return string|null
     */
    public function getUploadFileLink()
    {
        return $this->container['upload_file_link'];
    }

    /**
     * Sets upload_file_link
     *
     * @param string|null $upload_file_link upload_file_link
     *
     * @return self
     */
    public function setUploadFileLink($upload_file_link)
    {
        if (is_null($upload_file_link)) {
            throw new \InvalidArgumentException('non-nullable upload_file_link cannot be null');
        }
        $this->container['upload_file_link'] = $upload_file_link;

        return $this;
    }

    /**
     * Gets payroll_employees
     *
     * @return string[]|null
     */
    public function getPayrollEmployees()
    {
        return $this->container['payroll_employees'];
    }

    /**
     * Sets payroll_employees
     *
     * @param string[]|null $payroll_employees payroll_employees
     *
     * @return self
     */
    public function setPayrollEmployees($payroll_employees)
    {
        if (is_null($payroll_employees)) {
            throw new \InvalidArgumentException('non-nullable payroll_employees cannot be null');
        }
        $this->container['payroll_employees'] = $payroll_employees;

        return $this;
    }

    /**
     * Gets payroll_listing
     *
     * @return string|null
     */
    public function getPayrollListing()
    {
        return $this->container['payroll_listing'];
    }

    /**
     * Sets payroll_listing
     *
     * @param string|null $payroll_listing Get entries.
     *
     * @return self
     */
    public function setPayrollListing($payroll_listing)
    {
        if (is_null($payroll_listing)) {
            throw new \InvalidArgumentException('non-nullable payroll_listing cannot be null');
        }
        $this->container['payroll_listing'] = $payroll_listing;

        return $this;
    }

    /**
     * Gets allowances
     *
     * @return string[]|null
     */
    public function getAllowances()
    {
        return $this->container['allowances'];
    }

    /**
     * Sets allowances
     *
     * @param string[]|null $allowances allowances
     *
     * @return self
     */
    public function setAllowances($allowances)
    {
        if (is_null($allowances)) {
            throw new \InvalidArgumentException('non-nullable allowances cannot be null');
        }
        $this->container['allowances'] = $allowances;

        return $this;
    }

    /**
     * Gets timesheets
     *
     * @return string[]|null
     */
    public function getTimesheets()
    {
        return $this->container['timesheets'];
    }

    /**
     * Sets timesheets
     *
     * @param string[]|null $timesheets timesheets
     *
     * @return self
     */
    public function setTimesheets($timesheets)
    {
        if (is_null($timesheets)) {
            throw new \InvalidArgumentException('non-nullable timesheets cannot be null');
        }
        $this->container['timesheets'] = $timesheets;

        return $this;
    }

    /**
     * Gets timesheets_listing
     *
     * @return string|null
     */
    public function getTimesheetsListing()
    {
        return $this->container['timesheets_listing'];
    }

    /**
     * Sets timesheets_listing
     *
     * @param string|null $timesheets_listing timesheets_listing
     *
     * @return self
     */
    public function setTimesheetsListing($timesheets_listing)
    {
        if (is_null($timesheets_listing)) {
            throw new \InvalidArgumentException('non-nullable timesheets_listing cannot be null');
        }
        $this->container['timesheets_listing'] = $timesheets_listing;

        return $this;
    }

    /**
     * Gets bonis
     *
     * @return string[]|null
     */
    public function getBonis()
    {
        return $this->container['bonis'];
    }

    /**
     * Sets bonis
     *
     * @param string[]|null $bonis bonis
     *
     * @return self
     */
    public function setBonis($bonis)
    {
        if (is_null($bonis)) {
            throw new \InvalidArgumentException('non-nullable bonis cannot be null');
        }
        $this->container['bonis'] = $bonis;

        return $this;
    }

    /**
     * Gets to_string
     *
     * @return string|null
     */
    public function getToString()
    {
        return $this->container['to_string'];
    }

    /**
     * Sets to_string
     *
     * @param string|null $to_string to_string
     *
     * @return self
     */
    public function setToString($to_string)
    {
        if (is_null($to_string)) {
            throw new \InvalidArgumentException('non-nullable to_string cannot be null');
        }
        $this->container['to_string'] = $to_string;

        return $this;
    }

    /**
     * Gets total_employee_das_amount
     *
     * @return float|null
     */
    public function getTotalEmployeeDasAmount()
    {
        return $this->container['total_employee_das_amount'];
    }

    /**
     * Sets total_employee_das_amount
     *
     * @param float|null $total_employee_das_amount total_employee_das_amount
     *
     * @return self
     */
    public function setTotalEmployeeDasAmount($total_employee_das_amount)
    {
        if (is_null($total_employee_das_amount)) {
            throw new \InvalidArgumentException('non-nullable total_employee_das_amount cannot be null');
        }
        $this->container['total_employee_das_amount'] = $total_employee_das_amount;

        return $this;
    }

    /**
     * Gets total_employer_das_amount
     *
     * @return float|null
     */
    public function getTotalEmployerDasAmount()
    {
        return $this->container['total_employer_das_amount'];
    }

    /**
     * Sets total_employer_das_amount
     *
     * @param float|null $total_employer_das_amount total_employer_das_amount
     *
     * @return self
     */
    public function setTotalEmployerDasAmount($total_employer_das_amount)
    {
        if (is_null($total_employer_das_amount)) {
            throw new \InvalidArgumentException('non-nullable total_employer_das_amount cannot be null');
        }
        $this->container['total_employer_das_amount'] = $total_employer_das_amount;

        return $this;
    }

    /**
     * Gets total_provincial
     *
     * @return float|null
     */
    public function getTotalProvincial()
    {
        return $this->container['total_provincial'];
    }

    /**
     * Sets total_provincial
     *
     * @param float|null $total_provincial total_provincial
     *
     * @return self
     */
    public function setTotalProvincial($total_provincial)
    {
        if (is_null($total_provincial)) {
            throw new \InvalidArgumentException('non-nullable total_provincial cannot be null');
        }
        $this->container['total_provincial'] = $total_provincial;

        return $this;
    }

    /**
     * Gets total_federal
     *
     * @return float|null
     */
    public function getTotalFederal()
    {
        return $this->container['total_federal'];
    }

    /**
     * Sets total_federal
     *
     * @param float|null $total_federal total_federal
     *
     * @return self
     */
    public function setTotalFederal($total_federal)
    {
        if (is_null($total_federal)) {
            throw new \InvalidArgumentException('non-nullable total_federal cannot be null');
        }
        $this->container['total_federal'] = $total_federal;

        return $this;
    }

    /**
     * Gets employe_saving_taxable_reduction
     *
     * @return float|null
     */
    public function getEmployeSavingTaxableReduction()
    {
        return $this->container['employe_saving_taxable_reduction'];
    }

    /**
     * Sets employe_saving_taxable_reduction
     *
     * @param float|null $employe_saving_taxable_reduction employe_saving_taxable_reduction
     *
     * @return self
     */
    public function setEmployeSavingTaxableReduction($employe_saving_taxable_reduction)
    {
        if (is_null($employe_saving_taxable_reduction)) {
            throw new \InvalidArgumentException('non-nullable employe_saving_taxable_reduction cannot be null');
        }
        $this->container['employe_saving_taxable_reduction'] = $employe_saving_taxable_reduction;

        return $this;
    }

    /**
     * Gets custom_properties_listing
     *
     * @return string|null
     */
    public function getCustomPropertiesListing()
    {
        return $this->container['custom_properties_listing'];
    }

    /**
     * Sets custom_properties_listing
     *
     * @param string|null $custom_properties_listing custom_properties_listing
     *
     * @return self
     */
    public function setCustomPropertiesListing($custom_properties_listing)
    {
        if (is_null($custom_properties_listing)) {
            throw new \InvalidArgumentException('non-nullable custom_properties_listing cannot be null');
        }
        $this->container['custom_properties_listing'] = $custom_properties_listing;

        return $this;
    }

    /**
     * Gets api_shortname
     *
     * @return string|null
     */
    public function getApiShortname()
    {
        return $this->container['api_shortname'];
    }

    /**
     * Sets api_shortname
     *
     * @param string|null $api_shortname api_shortname
     *
     * @return self
     */
    public function setApiShortname($api_shortname)
    {
        if (is_null($api_shortname)) {
            throw new \InvalidArgumentException('non-nullable api_shortname cannot be null');
        }
        $this->container['api_shortname'] = $api_shortname;

        return $this;
    }

    /**
     * Gets table_name
     *
     * @return string|null
     */
    public function getTableName()
    {
        return $this->container['table_name'];
    }

    /**
     * Sets table_name
     *
     * @param string|null $table_name table_name
     *
     * @return self
     */
    public function setTableName($table_name)
    {
        if (is_null($table_name)) {
            throw new \InvalidArgumentException('non-nullable table_name cannot be null');
        }
        $this->container['table_name'] = $table_name;

        return $this;
    }

    /**
     * Gets full_entity_string
     *
     * @return string|null
     */
    public function getFullEntityString()
    {
        return $this->container['full_entity_string'];
    }

    /**
     * Sets full_entity_string
     *
     * @param string|null $full_entity_string full_entity_string
     *
     * @return self
     */
    public function setFullEntityString($full_entity_string)
    {
        if (is_null($full_entity_string)) {
            throw new \InvalidArgumentException('non-nullable full_entity_string cannot be null');
        }
        $this->container['full_entity_string'] = $full_entity_string;

        return $this;
    }

    /**
     * Gets anonymous_token
     *
     * @return string|null
     */
    public function getAnonymousToken()
    {
        return $this->container['anonymous_token'];
    }

    /**
     * Sets anonymous_token
     *
     * @param string|null $anonymous_token anonymous_token
     *
     * @return self
     */
    public function setAnonymousToken($anonymous_token)
    {
        if (is_null($anonymous_token)) {
            throw new \InvalidArgumentException('non-nullable anonymous_token cannot be null');
        }
        $this->container['anonymous_token'] = $anonymous_token;

        return $this;
    }

    /**
     * Gets token_string
     *
     * @return string|null
     */
    public function getTokenString()
    {
        return $this->container['token_string'];
    }

    /**
     * Sets token_string
     *
     * @param string|null $token_string token_string
     *
     * @return self
     */
    public function setTokenString($token_string)
    {
        if (is_null($token_string)) {
            throw new \InvalidArgumentException('non-nullable token_string cannot be null');
        }
        $this->container['token_string'] = $token_string;

        return $this;
    }

    /**
     * Gets entity_metatada_endpoint
     *
     * @return string|null
     */
    public function getEntityMetatadaEndpoint()
    {
        return $this->container['entity_metatada_endpoint'];
    }

    /**
     * Sets entity_metatada_endpoint
     *
     * @param string|null $entity_metatada_endpoint entity_metatada_endpoint
     *
     * @return self
     */
    public function setEntityMetatadaEndpoint($entity_metatada_endpoint)
    {
        if (is_null($entity_metatada_endpoint)) {
            throw new \InvalidArgumentException('non-nullable entity_metatada_endpoint cannot be null');
        }
        $this->container['entity_metatada_endpoint'] = $entity_metatada_endpoint;

        return $this;
    }

    /**
     * Gets files_listing
     *
     * @return string|null
     */
    public function getFilesListing()
    {
        return $this->container['files_listing'];
    }

    /**
     * Sets files_listing
     *
     * @param string|null $files_listing files_listing
     *
     * @return self
     */
    public function setFilesListing($files_listing)
    {
        if (is_null($files_listing)) {
            throw new \InvalidArgumentException('non-nullable files_listing cannot be null');
        }
        $this->container['files_listing'] = $files_listing;

        return $this;
    }

    /**
     * Gets modification_history_listing
     *
     * @return string|null
     */
    public function getModificationHistoryListing()
    {
        return $this->container['modification_history_listing'];
    }

    /**
     * Sets modification_history_listing
     *
     * @param string|null $modification_history_listing modification_history_listing
     *
     * @return self
     */
    public function setModificationHistoryListing($modification_history_listing)
    {
        if (is_null($modification_history_listing)) {
            throw new \InvalidArgumentException('non-nullable modification_history_listing cannot be null');
        }
        $this->container['modification_history_listing'] = $modification_history_listing;

        return $this;
    }

    /**
     * Gets notes_listing
     *
     * @return string|null
     */
    public function getNotesListing()
    {
        return $this->container['notes_listing'];
    }

    /**
     * Sets notes_listing
     *
     * @param string|null $notes_listing notes_listing
     *
     * @return self
     */
    public function setNotesListing($notes_listing)
    {
        if (is_null($notes_listing)) {
            throw new \InvalidArgumentException('non-nullable notes_listing cannot be null');
        }
        $this->container['notes_listing'] = $notes_listing;

        return $this;
    }

    /**
     * Gets ownerships_listing
     *
     * @return string|null
     */
    public function getOwnershipsListing()
    {
        return $this->container['ownerships_listing'];
    }

    /**
     * Sets ownerships_listing
     *
     * @param string|null $ownerships_listing ownerships_listing
     *
     * @return self
     */
    public function setOwnershipsListing($ownerships_listing)
    {
        if (is_null($ownerships_listing)) {
            throw new \InvalidArgumentException('non-nullable ownerships_listing cannot be null');
        }
        $this->container['ownerships_listing'] = $ownerships_listing;

        return $this;
    }

    /**
     * Gets approvals_listing
     *
     * @return string|null
     */
    public function getApprovalsListing()
    {
        return $this->container['approvals_listing'];
    }

    /**
     * Sets approvals_listing
     *
     * @param string|null $approvals_listing approvals_listing
     *
     * @return self
     */
    public function setApprovalsListing($approvals_listing)
    {
        if (is_null($approvals_listing)) {
            throw new \InvalidArgumentException('non-nullable approvals_listing cannot be null');
        }
        $this->container['approvals_listing'] = $approvals_listing;

        return $this;
    }

    /**
     * Gets f_qcn
     *
     * @return string|null
     */
    public function getFQcn()
    {
        return $this->container['f_qcn'];
    }

    /**
     * Sets f_qcn
     *
     * @param string|null $f_qcn f_qcn
     *
     * @return self
     */
    public function setFQcn($f_qcn)
    {
        if (is_null($f_qcn)) {
            throw new \InvalidArgumentException('non-nullable f_qcn cannot be null');
        }
        $this->container['f_qcn'] = $f_qcn;

        return $this;
    }

    /**
     * Gets unique_id
     *
     * @return string|null
     */
    public function getUniqueId()
    {
        return $this->container['unique_id'];
    }

    /**
     * Sets unique_id
     *
     * @param string|null $unique_id unique_id
     *
     * @return self
     */
    public function setUniqueId($unique_id)
    {
        if (is_null($unique_id)) {
            throw new \InvalidArgumentException('non-nullable unique_id cannot be null');
        }
        $this->container['unique_id'] = $unique_id;

        return $this;
    }

    /**
     * Gets api_custom_data
     *
     * @return mixed|null
     */
    public function getApiCustomData()
    {
        return $this->container['api_custom_data'];
    }

    /**
     * Sets api_custom_data
     *
     * @param mixed|null $api_custom_data api_custom_data
     *
     * @return self
     */
    public function setApiCustomData($api_custom_data)
    {
        if (is_null($api_custom_data)) {
            array_push($this->openAPINullablesSetToNull, 'api_custom_data');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('api_custom_data', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['api_custom_data'] = $api_custom_data;

        return $this;
    }

    /**
     * Gets timestamp
     *
     * @return \DateTime|null
     */
    public function getTimestamp()
    {
        return $this->container['timestamp'];
    }

    /**
     * Sets timestamp
     *
     * @param \DateTime|null $timestamp Get createdAt.
     *
     * @return self
     */
    public function setTimestamp($timestamp)
    {
        if (is_null($timestamp)) {
            throw new \InvalidArgumentException('non-nullable timestamp cannot be null');
        }
        $this->container['timestamp'] = $timestamp;

        return $this;
    }

    /**
     * Gets deleted
     *
     * @return bool|null
     */
    public function getDeleted()
    {
        return $this->container['deleted'];
    }

    /**
     * Sets deleted
     *
     * @param bool|null $deleted Check if the entity has been soft deleted.
     *
     * @return self
     */
    public function setDeleted($deleted)
    {
        if (is_null($deleted)) {
            throw new \InvalidArgumentException('non-nullable deleted cannot be null');
        }
        $this->container['deleted'] = $deleted;

        return $this;
    }

    /**
     * Gets taggable_type
     *
     * @return string|null
     */
    public function getTaggableType()
    {
        return $this->container['taggable_type'];
    }

    /**
     * Sets taggable_type
     *
     * @param string|null $taggable_type taggable_type
     *
     * @return self
     */
    public function setTaggableType($taggable_type)
    {
        if (is_null($taggable_type)) {
            array_push($this->openAPINullablesSetToNull, 'taggable_type');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('taggable_type', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['taggable_type'] = $taggable_type;

        return $this;
    }

    /**
     * Gets taggable_id
     *
     * @return int|null
     */
    public function getTaggableId()
    {
        return $this->container['taggable_id'];
    }

    /**
     * Sets taggable_id
     *
     * @param int|null $taggable_id taggable_id
     *
     * @return self
     */
    public function setTaggableId($taggable_id)
    {
        if (is_null($taggable_id)) {
            throw new \InvalidArgumentException('non-nullable taggable_id cannot be null');
        }
        $this->container['taggable_id'] = $taggable_id;

        return $this;
    }

    /**
     * Gets tagging_listing
     *
     * @return string|null
     */
    public function getTaggingListing()
    {
        return $this->container['tagging_listing'];
    }

    /**
     * Sets tagging_listing
     *
     * @param string|null $tagging_listing Get Tagging Listing Why this crashes get annotations (proxy class?)
     *
     * @return self
     */
    public function setTaggingListing($tagging_listing)
    {
        if (is_null($tagging_listing)) {
            throw new \InvalidArgumentException('non-nullable tagging_listing cannot be null');
        }
        $this->container['tagging_listing'] = $tagging_listing;

        return $this;
    }

    /**
     * Gets enabled
     *
     * @return bool|null
     */
    public function getEnabled()
    {
        return $this->container['enabled'];
    }

    /**
     * Sets enabled
     *
     * @param bool|null $enabled Check if the entity is enabled.
     *
     * @return self
     */
    public function setEnabled($enabled)
    {
        if (is_null($enabled)) {
            throw new \InvalidArgumentException('non-nullable enabled cannot be null');
        }
        $this->container['enabled'] = $enabled;

        return $this;
    }

    /**
     * Gets enabled_virtual
     *
     * @return bool|null
     */
    public function getEnabledVirtual()
    {
        return $this->container['enabled_virtual'];
    }

    /**
     * Sets enabled_virtual
     *
     * @param bool|null $enabled_virtual Virtual isEnabled property.
     *
     * @return self
     */
    public function setEnabledVirtual($enabled_virtual)
    {
        if (is_null($enabled_virtual)) {
            throw new \InvalidArgumentException('non-nullable enabled_virtual cannot be null');
        }
        $this->container['enabled_virtual'] = $enabled_virtual;

        return $this;
    }

    /**
     * Gets disabled
     *
     * @return bool|null
     */
    public function getDisabled()
    {
        return $this->container['disabled'];
    }

    /**
     * Sets disabled
     *
     * @param bool|null $disabled Check if the entit is enabled.
     *
     * @return self
     */
    public function setDisabled($disabled)
    {
        if (is_null($disabled)) {
            throw new \InvalidArgumentException('non-nullable disabled cannot be null');
        }
        $this->container['disabled'] = $disabled;

        return $this;
    }

    /**
     * Gets upload_subfolder
     *
     * @return string|null
     */
    public function getUploadSubfolder()
    {
        return $this->container['upload_subfolder'];
    }

    /**
     * Sets upload_subfolder
     *
     * @param string|null $upload_subfolder upload_subfolder
     *
     * @return self
     */
    public function setUploadSubfolder($upload_subfolder)
    {
        if (is_null($upload_subfolder)) {
            throw new \InvalidArgumentException('non-nullable upload_subfolder cannot be null');
        }
        $this->container['upload_subfolder'] = $upload_subfolder;

        return $this;
    }

    /**
     * Gets upload_file
     *
     * @return string|null
     */
    public function getUploadFile()
    {
        return $this->container['upload_file'];
    }

    /**
     * Sets upload_file
     *
     * @param string|null $upload_file upload_file
     *
     * @return self
     */
    public function setUploadFile($upload_file)
    {
        if (is_null($upload_file)) {
            throw new \InvalidArgumentException('non-nullable upload_file cannot be null');
        }
        $this->container['upload_file'] = $upload_file;

        return $this;
    }

    /**
     * Gets upload_file_link
     *
     * @return string|null
     */
    public function getUploadFileLink()
    {
        return $this->container['upload_file_link'];
    }

    /**
     * Sets upload_file_link
     *
     * @param string|null $upload_file_link upload_file_link
     *
     * @return self
     */
    public function setUploadFileLink($upload_file_link)
    {
        if (is_null($upload_file_link)) {
            throw new \InvalidArgumentException('non-nullable upload_file_link cannot be null');
        }
        $this->container['upload_file_link'] = $upload_file_link;

        return $this;
    }

    /**
     * Gets entity_storage_folder
     *
     * @return string|null
     */
    public function getEntityStorageFolder()
    {
        return $this->container['entity_storage_folder'];
    }

    /**
     * Sets entity_storage_folder
     *
     * @param string|null $entity_storage_folder entity_storage_folder
     *
     * @return self
     */
    public function setEntityStorageFolder($entity_storage_folder)
    {
        if (is_null($entity_storage_folder)) {
            throw new \InvalidArgumentException('non-nullable entity_storage_folder cannot be null');
        }
        $this->container['entity_storage_folder'] = $entity_storage_folder;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


